### PR TITLE
[backport][ses5] qa: refactor health-ok.sh, introduce storage profile and Stage 5 tests

### PR DESCRIPTION
**Pull request by smithfarm**
**Checklist:**
~~- [ ] Added unittests and or functional tests~~
~~- [ ] Adapted documentation~~
~~- [ ] Referenced issues or internal bugtracker~~
~~- [ ] cherry-pick #1297 into this PR~~
- [x] Enable susebot to trigger custom suites, e.g.  `@susebot run teuthology for suse/tier2`
- [x] Test suse/tier1/functional
- [x] Test suse/tier2
- [x] port health-igw.sh, health-nfs-ganesha.sh, and health-openattic.sh to health-ok.sh
- [x] suse/tier1/igw and suse/tier1/nfs-ganesha pass
- [x] forward-port health-nfs-ganesha.sh migration to master (as part of https://github.com/SUSE/DeepSea/pull/1305)
- [x] suse/tier1/openattic passes
- [x] open PR with forward-port of "qa: more flexible role assignment in policy.cfg"
- [x] add more CLI test cases
- [x] https://github.com/SUSE/DeepSea/pull/1257 merged
- [x] cherry-pick `--no-update` patch from #1308
- [x] Adapt deepsea-pr.sh to run `suse/tier1` instead of `suse/smoke`
- [x] suse/tier1 running "acceptably"
- [x] Merge SUSE/ceph.git wip-qa-ses5 into ses5
- [x] Ran integration tests successfully ( trigger with @susebot run teuthology )

### CODE REVIEW

**Comment by smithfarm** [comment]
This needs to be tested (and merged) together with SUSE/ceph.git `wip-qa-ses5` (just saying).

Test results:

* `suse/tier1` http://137.74.25.20:8081/ubuntu-2018-08-20_15:26:00-suse:tier1-ses5---basic-openstack/
* `suse/tier2` http://137.74.25.20:8081/ubuntu-2018-08-20_14:26:02-suse:tier2-ses5---basic-openstack/

**Comment by smithfarm** [comment]
@jschmid1 Please note that the DeepSea branch used in the test results detailed in the previous comment is based on today's SES5 - i.e. it includes `backport-1222` and `backport-1259` branches.

**Comment by jschmid1** [comment]
Thanks @smithfarm. Comparing the two tier2 results actually shows reproducible problems with:

* --profile=fs_dedicated_journal
* --profile=bs_dedicated_db_sizes
* --profile=bs_dedicated_wal_sizes
* --profile=fs_dedicated_journal_crypt

Investigation time..

**Comment by smithfarm** [comment]
Analysis of failed jobs from the first `suse/tier1` run, above:

* func-replace.yaml failed because #1258 was not merged yet
* func-migrate.yaml failed because #1258 was not merged yet (and it's known to not (quite) pass even with that PR)
* health-ok-stage-5.yaml failed because #1297 was not merged or backported yet (now merged, still not backported)
* health-ok with random profile failed because bs_dedicated_db_sizes.yaml was chosen (known to fail in SES5)
* health-rgw-ssl.yaml failed due to "Stage 3 timed out after 30m" (known transient issue unrelated to this PR)
* functional.yaml *also* failed due to "Stage 3 timed out after 30m" (known transient issue unrelated to this PR)

**Comment by smithfarm** [comment]
New round of testing:

* `suse/tier1/functional` http://137.74.25.20:8081/ubuntu-2018-08-23_11:13:46-suse:tier1:functional-ses5---basic-openstack/ **PASS** (2 jobs)
* `suse/tier1` http://137.74.25.20:8081/ubuntu-2018-08-23_11:40:43-suse:tier1-ses5---basic-openstack/ **RUNNING** (14 jobs)

**Comment by smithfarm** [comment]
More testing:

* `suse/tier1/igw` http://137.74.25.20:8081/ubuntu-2018-08-23_14:25:48-suse:tier1:igw-ses5---basic-openstack/ **PASS** (1 job total)
* `suse/tier1/nfs-ganesha` http://137.74.25.20:8081/ubuntu-2018-08-23_14:25:18-suse:tier1:nfs-ganesha-ses5---basic-openstack/ **PASS** (3 jobs total)

**Comment by smithfarm** [comment]
This is almost ready. Will put finishing touches on it tomorrow (Friday).

**Comment by smithfarm** [comment]
@jschmid1 Would it make sense to cherry-pick #1297 into this PR since that fixes one of the failing tier1 tests, or would you rather have a separate backport PR for that?

**Comment by jschmid1** [comment]
> @jschmid1 Would it make sense to cherry-pick #1297 into this PR since that fixes one of the failing tier1 tests, or would you rather have a separate backport PR for that?

@smithfarm 
Yes, let's combine all the QA related backports. That makes it easier to test altogether

**Comment by smithfarm** [comment]
@jschmid1 This PR is getting pretty big and unwieldy, and #1297 backport looks a little tricky. Not having it here only causes one test failure.

**Comment by smithfarm** [comment]
Full `suse/tier1` run: http://137.74.25.20:8081/ubuntu-2018-08-24_12:05:49-suse:tier1-ses5---basic-openstack/

Result: 14 PASS, 1 FAIL (15 total). The failed job is suse/tier1/stage-5 (needs backport of #1297)

I think this is ready to go in.

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
http://167.114.237.168:8081/ubuntu-2018-08-24_14:08:34-suse:tier1-ses5---basic-openstack/

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
The last run is what I was looking for. Merging.

**Pull request merged**
