### PR TITLE
[tmp] fix to run the ci against

### PR DESCRIPTION
**Pull request by jschmid1**
Signed-off-by: Joshua Schmid <jschmid@suse.de>

see #1747 for more infos

-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [ ] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
That seem to fix the issues we've seen in the `disk replacement` and `rebuild` tests. I'll come up with a proper fix that's also backwards compatible

**Comment by jan--f** [comment]
hmm I think this might only mask the issue. ceph-volume in 14.2.3 actually fails to zap disks when run through salt. will test a fix today.

**Comment by jschmid1** [comment]
skipped 14.2.3 -> now using 14.2.4 which fixed the issues @jan--f described. closing

**Pull request closed without merging**
