### PR TITLE
cli: refer to orchestration instead of stage

### PR DESCRIPTION
**Pull request by smithfarm**
The deepsea cli can be used to run any orchestration, not just ceph.stage.*

-----------------

**Checklist:**
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by smithfarm** [comment]
Waiting for deepsea-make-rpm Dockerization to be able to test this.

**Comment by smithfarm** [comment]
@susebot run teuthology deepsea/tier2/health-ok

**Comment by jschmid1** [comment]
@susebot run teuthology deepsea/tier2/health-ok

**Comment by jschmid1** [comment]
related? 

> http://ceph-ci.suse.de:8080/job/deepsea-pr/170/testReport/teuthology/deepsea_tier2_health-ok/_ceph_cm_salt_yaml_cluster__1node_yaml_4disks_yaml__deepsea_yaml_distros_sle_15_0_yaml_tasks_custom_profile_yaml_/

**Comment by smithfarm** [comment]
@jschmid1 No, not related. That failure is https://github.com/SUSE/DeepSea/issues/1382

```
2018-09-24T14:10:49.155 INFO:tasks.workunit.client.salt_master.target213032028028.stderr:+ timeout 60m salt-run --no-color state.orch ceph.stage.3
2018-09-24T14:10:49.156 INFO:tasks.workunit.client.salt_master.target213032028028.stderr:+ tee /tmp/stage.3.log
2018-09-24T15:10:49.166 INFO:tasks.workunit.client.salt_master.target213032028028.stdout:WWWW
2018-09-24T15:10:49.168 INFO:tasks.workunit.client.salt_master.target213032028028.stdout:********** Stage 3 failed **********
2018-09-24T15:10:49.168 INFO:tasks.workunit.client.salt_master.target213032028028.stdout:Stage 3 timed out after 60m
```

**Comment by smithfarm** [comment]
This [1] is the relevant test case, and it passed.

[1] http://ceph-ci.suse.de:8080/job/deepsea-pr/170/testReport/teuthology/deepsea_tier2_health-ok/_ceph_cm_salt_yaml_cluster__1node_yaml_4disks_yaml__deepsea_yaml_distros_sle_15_0_yaml_tasks_default_profile_cli_yaml_/

**Comment by smithfarm** [comment]
@jschmid1 Backport is desirable, I guess, but not absolutely necessary.

**Pull request merged**
