### PR TITLE
validate: use setdefault when creating error lists

### PR DESCRIPTION
**Pull request by theanalyst**
Refactoring validate.py to use setdefault while creating error lists

### CODE REVIEW

**Comment by theanalyst** [comment]
Also setting the pass status as a function which checks for error values in dictionary

**Comment by theanalyst** [comment]
TODO: use `_set_pass_status` for fqdn, pending merge of #84

**Comment by theanalyst** [comment]
added a very basic test to validate

**Comment by theanalyst** [comment]
I guess this is ready for an initial review

**Comment by theanalyst** [comment]
@jschmid1 can you take a look at the mock tests

**Comment by jschmid1** [comment]
I'm trying to figure out the pros and cons.. let's move the discussion to the mailinglist

**Comment by jschmid1** [comment]
followup: http://lists.suse.com/pipermail/deepsea-users/2017-January/000073.html

**Pull request merged**
