### PR TITLE
Test the rebuild within Teuthology

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <ejackson@suse.com>

-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [ ] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
This seems like a proper issue with the tests.. I also assume that having one OSD node might not suffice for a test that wipes half of the data :dagger:

**Comment by jschmid1** [comment]
@swiftgist can you take care of adjusting the tests?

**Comment by swiftgist** [comment]
I thought we might discuss this at the meeting... does the teuthology for DeepSea support more than one node?  The rebuild test works fine if there's more than one OSD.

**Comment by jschmid1** [comment]
this will be tested in #1710

**Pull request closed without merging**
