### PR TITLE
lvm batch refactor adaption

### PR DESCRIPTION
**Pull request by jschmid1**
This is needed for the latest version of ceph

-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [ ] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jan--f** [comment]
I don't think our nautilus version ships the refactored code yet, but I'll double check. But might be we want to postpone this a little bit.

**Comment by smithfarm** [comment]
> I don't think our nautilus version ships the refactored code yet

Correct

**Comment by jschmid1** [comment]
Please leave a comment here if it does

**Review by jan--f — APPROVED** [review]
LGTM

**Comment by jan--f** [comment]
https://github.com/ceph/ceph/pull/37522 is merged. I suppose we can cut a new package on top of 0.9.32?

**Pull request merged**
