### PR TITLE
Support forced restart

### PR DESCRIPTION
**Pull request by swiftgist**
HEALTH_ERR will stop the orchestration, but the restart will ignore
individual restart failures.

Signed-off-by: Eric Jackson <ejackson@suse.com>
~bnc#1110249~
jschmid edit: bsc#1099577

Functional tests are already covered for forced restarts
-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [x] Adapted documentation
- [x] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
This is new @smithfarm @kshtsk :)

>   File "/home/ubuntu/teuthology/teuthology/openstack/__init__.py", line 363, in image_create
    misc.sh("wget -c -O " + name + ".qcow2 " + self.image2url[name])
KeyError: 'sle-15.0-x86_64'

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology

**Pull request merged**
