### PR TITLE
cli: filter out test.nop steps and don't report [init] step errors

### PR DESCRIPTION
**Pull request by rjfd**
Fixes: #1243

Description:

This PR introduces the following changes to fix the problems reported in #1243 
* filter out test.nop states from the execution plan
* [init] step errors are not reported in the failure summary

### CODE REVIEW

**Comment by smithfarm** [comment]
Testing (hopefully) here: http://137.74.25.20:8081/ubuntu-2018-07-27_11:58:48-suse:smoke:health-ok-wip-qa-osd-config---basic-openstack/85/

**Comment by smithfarm** [comment]
Relevant log excerpt:

```
2018-07-27T12:04:44.862 INFO:teuthology.orchestra.run.target137074030237.stderr:+ deepsea --log-file=/var/log/salt/deepsea.log --log-level=debug stage run ceph.stage.0 --simple-output
2018-07-27T12:04:44.862 INFO:teuthology.orchestra.run.target137074030237.stderr:+ tee /tmp/deepsea.0.log
2018-07-27T12:04:45.489 INFO:teuthology.orchestra.run.target137074030237.stdout:Starting stage: ceph.stage.0
2018-07-27T12:10:57.034 INFO:teuthology.orchestra.run.target137074030237.stdout:Parsing stage ceph.stage.0 steps... done
2018-07-27T12:10:57.035 INFO:teuthology.orchestra.run.target137074030237.stdout:
2018-07-27T12:10:57.035 INFO:teuthology.orchestra.run.target137074030237.stdout:Stage initialization output:
2018-07-27T12:10:57.035 INFO:teuthology.orchestra.run.target137074030237.stdout:deepsea_minions          : [1m[92mvalid[0m
2018-07-27T12:10:57.035 INFO:teuthology.orchestra.run.target137074030237.stdout:master_minion            : [1m[92mvalid[0m
2018-07-27T12:10:57.035 INFO:teuthology.orchestra.run.target137074030237.stdout:ceph_version             : [1m[92mvalid[0m
2018-07-27T12:10:57.035 INFO:teuthology.orchestra.run.target137074030237.stdout:salt_version             : [1m[92mvalid[0m
2018-07-27T12:10:57.035 INFO:teuthology.orchestra.run.target137074030237.stdout:
2018-07-27T12:10:57.036 INFO:teuthology.orchestra.run.target137074030237.stdout:[init] Executing runner validate.setup...
2018-07-27T12:10:57.036 INFO:teuthology.orchestra.run.target137074030237.stdout:         |_  pkg.info_installed(ceph-common)...
2018-07-27T12:10:57.036 INFO:teuthology.orchestra.run.target137074030237.stdout:               in target137074030237.teuthology... fail
2018-07-27T12:10:57.036 INFO:teuthology.orchestra.run.target137074030237.stdout:         |_  pkg.info_available(ceph-common)...
2018-07-27T12:10:57.036 INFO:teuthology.orchestra.run.target137074030237.stdout:               in target137074030237.teuthology... ok
2018-07-27T12:10:57.036 INFO:teuthology.orchestra.run.target137074030237.stdout:[init] Executing runner validate.setup... ok
2018-07-27T12:10:57.036 INFO:teuthology.orchestra.run.target137074030237.stdout:[init] Executing runner advise.salt_run... ok
2018-07-27T12:10:57.036 INFO:teuthology.orchestra.run.target137074030237.stdout:[init] Executing runner cephprocesses.mon... ok
2018-07-27T12:10:57.037 INFO:teuthology.orchestra.run.target137074030237.stdout:
2018-07-27T12:10:57.037 INFO:teuthology.orchestra.run.target137074030237.stdout:[1/14] Executing state ceph.sync...
2018-07-27T12:10:57.037 INFO:teuthology.orchestra.run.target137074030237.stdout:         |_  target137074030237.teuthology: load modules(saltutil.sync_all) ok
2018-07-27T12:10:57.037 INFO:teuthology.orchestra.run.target137074030237.stdout:         target137074030237.teuthology... ok
2018-07-27T12:10:57.037 INFO:teuthology.orchestra.run.target137074030237.stdout:[2/14] Executing state ceph.salt-api...
2018-07-27T12:10:57.037 INFO:teuthology.orchestra.run.target137074030237.stdout:         |_  target137074030237.teuthology: salt-api ok
2018-07-27T12:10:57.037 INFO:teuthology.orchestra.run.target137074030237.stdout:         target137074030237.teuthology... ok
2018-07-27T12:10:57.037 INFO:teuthology.orchestra.run.target137074030237.stdout:[3/14] Executing state ceph.repo...
2018-07-27T12:10:57.037 INFO:teuthology.orchestra.run.target137074030237.stdout:         target137074030237.teuthology... ok
2018-07-27T12:10:57.038 INFO:teuthology.orchestra.run.target137074030237.stdout:[4/14] Executing state ceph.metapackage...
2018-07-27T12:10:57.038 INFO:teuthology.orchestra.run.target137074030237.stdout:         target137074030237.teuthology... ok
2018-07-27T12:10:57.038 INFO:teuthology.orchestra.run.target137074030237.stdout:[5/14] Executing state ceph.updates...
2018-07-27T12:10:57.038 INFO:teuthology.orchestra.run.target137074030237.stdout:         |_  target137074030237.teuthology: packagemanager patch only kernel(packagemanager.up) ok
2018-07-27T12:10:57.038 INFO:teuthology.orchestra.run.target137074030237.stdout:         |_  target137074030237.teuthology: packagemanager update regular(packagemanager.up) ok
2018-07-27T12:10:57.038 INFO:teuthology.orchestra.run.target137074030237.stdout:         target137074030237.teuthology... ok
2018-07-27T12:10:57.038 INFO:teuthology.orchestra.run.target137074030237.stdout:[6/14] Executing runner filequeue.remove... ok
2018-07-27T12:10:57.038 INFO:teuthology.orchestra.run.target137074030237.stdout:[7/14] Executing runner filequeue.enqueue... ok
2018-07-27T12:10:57.038 INFO:teuthology.orchestra.run.target137074030237.stdout:[8/14] Executing runner minions.ready...
2018-07-27T12:10:57.038 INFO:teuthology.orchestra.run.target137074030237.stdout:         |_  test.ping()...
2018-07-27T12:10:57.039 INFO:teuthology.orchestra.run.target137074030237.stdout:               in target137074030237.teuthology... ok
2018-07-27T12:10:57.039 INFO:teuthology.orchestra.run.target137074030237.stdout:[8/14] Executing runner minions.ready... ok
2018-07-27T12:10:57.039 INFO:teuthology.orchestra.run.target137074030237.stdout:[9/14] Executing state ceph.repo...
2018-07-27T12:10:57.039 INFO:teuthology.orchestra.run.target137074030237.stdout:         target137074030237.teuthology... ok
2018-07-27T12:10:57.039 INFO:teuthology.orchestra.run.target137074030237.stdout:[10/14] Executing state ceph.metapackage...
2018-07-27T12:10:57.039 INFO:teuthology.orchestra.run.target137074030237.stdout:         target137074030237.teuthology... ok
2018-07-27T12:10:57.039 INFO:teuthology.orchestra.run.target137074030237.stdout:[11/14] Executing state ceph.packages.common...
2018-07-27T12:10:57.039 INFO:teuthology.orchestra.run.target137074030237.stdout:         |_  target137074030237.teuthology: stage prep dependencies suse ok
2018-07-27T12:10:57.039 INFO:teuthology.orchestra.run.target137074030237.stdout:         target137074030237.teuthology... ok
2018-07-27T12:10:57.040 INFO:teuthology.orchestra.run.target137074030237.stdout:[12/14] Executing state ceph.sync...
2018-07-27T12:10:57.040 INFO:teuthology.orchestra.run.target137074030237.stdout:         |_  target137074030237.teuthology: load modules(saltutil.sync_all) ok
2018-07-27T12:10:57.040 INFO:teuthology.orchestra.run.target137074030237.stdout:         target137074030237.teuthology... ok
2018-07-27T12:10:57.040 INFO:teuthology.orchestra.run.target137074030237.stdout:[13/14] Executing state ceph.mines...
2018-07-27T12:10:57.040 INFO:teuthology.orchestra.run.target137074030237.stdout:         |_  target137074030237.teuthology: configure_mine_functions_conf(/etc/salt/minion.d/mine_functions.conf) ok
2018-07-27T12:10:57.040 INFO:teuthology.orchestra.run.target137074030237.stdout:         |_  target137074030237.teuthology: manage_salt_minion_for_mines(mine.update) ok
2018-07-27T12:10:57.040 INFO:teuthology.orchestra.run.target137074030237.stdout:         target137074030237.teuthology... ok
2018-07-27T12:10:57.040 INFO:teuthology.orchestra.run.target137074030237.stdout:[14/14] Executing state ceph.updates...
2018-07-27T12:10:57.041 INFO:teuthology.orchestra.run.target137074030237.stdout:         |_  target137074030237.teuthology: packagemanager patch only kernel(packagemanager.up) ok
2018-07-27T12:10:57.041 INFO:teuthology.orchestra.run.target137074030237.stdout:         |_  target137074030237.teuthology: packagemanager update regular(packagemanager.up) ok
2018-07-27T12:10:57.041 INFO:teuthology.orchestra.run.target137074030237.stdout:         target137074030237.teuthology... ok
2018-07-27T12:10:57.041 INFO:teuthology.orchestra.run.target137074030237.stdout:Finished stage ceph.stage.0: succeeded=14/14 failed=0/14
2018-07-27T12:10:57.146 INFO:teuthology.orchestra.run.target137074030237.stdout:deepsea exit status: 0
```

**Comment by smithfarm** [comment]
@jschmid1 Backport only needed if CLI is broken in SES5?

**Comment by jschmid1** [comment]
@smithfarm iirc we have the same CLI implementation in SES5 ( minus some salt version tweaks ).. We need to verify if that appears to be an issue on salt2016 aswell.

**Comment by smithfarm** [comment]
@jschmid1 I was just testing ceph 12.2.7 and ran deepsea/basic on it, and the CLI tests are green there: http://137.74.25.20:8081/ubuntu-2018-07-25_19:31:41-deepsea:basic-ses5---basic-openstack/

So I don't think this is needed in SES5 - at least not now.

**Pull request merged**
