### PR TITLE
spec/fix: add new Prometheus RGW exporter files

### PR DESCRIPTION
**Pull request by carltonf**
This commit adds needed SPEC changes for SR#805:
> Refactor Prometheus RGW exporter customization according to the DeepSea conventions.

### CODE REVIEW

**Comment by votdev** [comment]
Thx for adding the missing changes in the spec file.

**Comment by rjfd** [comment]
I have one question. PR #805 removed `/srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter.sls` and added a new directory `/srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter`, which is being added to the spec file in this PR.

When updating deepsea, the old `/srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter.sls` file will remain and Salt will use it in favor of the new directory. Is there a way to specify in the spec file that the `/srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter.sls` file must be deleted during an update?

@smithfarm @votdev @carltonf

**Comment by smithfarm** [comment]
@rjfd Yes, with something like this:

```
%postun
if [ $1 -ge 1 ] ; then
  rm -rf /srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter.sls
fi
```

@carltonf Could you add that to this PR?

**Comment by votdev** [comment]
What about the Makefile?

**Comment by smithfarm** [comment]
Actually, if `/srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter.sls` is no longer used at all, maybe we should delete it in `%postun` unconditionally? I.e. so it is deleted upon update *and* remove.

**Comment by rjfd** [comment]
> What about the Makefile?

The makefile is only used for development. We don't need to support upgrades :)

**Comment by rjfd** [comment]
@smithfarm 
> Actually, if /srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter.sls is no longer used at all, maybe we should delete it in %postun unconditionally?

Yes

**Comment by carltonf** [comment]
> the /srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter.sls file must be deleted during an update?

It's not necessary to manually remove old files, the RPM update process will do it automatically.

The update process is:
> 1. Installs the desired package.
> 2. Erases all older versions of the package, if any exist.

The erasure process will : 
> It reviews the RPM database to find every file listed as being part of the package, and if they do not belong to another package, deletes them.

/srv/salt/ceph/monitoring/prometheus/exporters/ceph_rgw_exporter.sls will not be listed as part of the new Deepsea package so it will be deleted automatically.

See http://ftp.rpm.org/max-rpm/ch-rpm-upgrade.html

**Comment by rjfd** [comment]
@carltonf great! one less thing to worry

**Pull request merged**
