### PR TITLE
drivegroups: allow lower case sizing units

### PR DESCRIPTION
**Pull request by jschmid1**
-----------------

**Checklist:**
- [x] Added unittests and or functional tests
~- [ ] Adapted documentation~
~- [ ] Referenced issues or internal bugtracker~
- [x] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
could you please fix these tests @kshtsk @smithfarm 

```
CommandFailedError: Command failed (dashboard_e2e_tests.sh) on target192168000049 with status 127: 'sudo bash scripts/dashboard_e2e_tests.sh'
```

**Comment by smithfarm** [comment]
ceph-dashboard-e2e RPM version in the test is 14.2.1.470+g3f660f71d4
which is behind Devel:Storage:6.0, where we have 14.2.1.475+g83b977ffbd

@kshtsk Please update the artifacts to the latest.

**Comment by kshtsk** [comment]
@susebot run teuthology

**Pull request merged**
