### PR TITLE
[backport][SES6] 'make pyc' target should fail if unable to compile

### PR DESCRIPTION
**Pull request by mgfritch**
Backport of #1770

### CODE REVIEW

**Comment by mgfritch** [comment]
@susebot run teuthology

**Comment by mgfritch** [comment]
> Commit [589bc84](https://github.com/SUSE/DeepSea/commit/589bc840dd0111b3137294da66d3e8274b5ab2fb) is _NOT OK_ for suite deepsea:tier2.
> Check tests results in the Jenkins job: http://ci.ses.suse.de:8080/job/pr-deepsea/330/

Will be OK when #1779 is backported.

**Comment by jschmid1** [comment]
#1779 is merged, please rebase and run the tests again

**Comment by mgfritch** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
There seems to be an issue with the migration logic still:

```
2019-10-11T07:58:59.149 INFO:tasks.deepsea.toolbox:Disengaging safety to prepare for rebuild
2019-10-11T07:58:59.150 INFO:teuthology.orchestra.run.target192168000080:Running: 'sudo salt-run disengage.safety 2>/dev/null'
2019-10-11T07:59:21.955 INFO:teuthology.orchestra.run.target192168000080.stdout:safety is now disabled for cluster ceph
2019-10-11T07:59:21.956 INFO:tasks.deepsea.toolbox:Rebuilding node target192168000080.teuthology
2019-10-11T07:59:21.957 INFO:teuthology.orchestra.run.target192168000080:Running: 'sudo salt-run rebuild.node target192168000080.teuthology 2>/dev/null'
2019-10-11T07:59:53.694 INFO:teuthology.orchestra.run.target192168000080.stdout:The following minions were skipped:
2019-10-11T07:59:53.695 INFO:teuthology.orchestra.run.target192168000080.stdout:target192168000080.teuthology
2019-10-11T07:59:53.695 INFO:teuthology.orchestra.run.target192168000080.stdout:
2019-10-11T07:59:53.695 INFO:teuthology.orchestra.run.target192168000080.stdout:Resolve any issues and run
2019-10-11T07:59:53.695 INFO:teuthology.orchestra.run.target192168000080.stdout: salt-run rebuild.nodes target192168000080.teuthology
``` 
would you have a look @swiftgist or @mgfritch ?

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by mgfritch** [comment]
> There seems to be an issue with the migration logic still:
> 
> ```
> 2019-10-11T07:58:59.149 INFO:tasks.deepsea.toolbox:Disengaging safety to prepare for rebuild
> 2019-10-11T07:58:59.150 INFO:teuthology.orchestra.run.target192168000080:Running: 'sudo salt-run disengage.safety 2>/dev/null'
> 2019-10-11T07:59:21.955 INFO:teuthology.orchestra.run.target192168000080.stdout:safety is now disabled for cluster ceph
> 2019-10-11T07:59:21.956 INFO:tasks.deepsea.toolbox:Rebuilding node target192168000080.teuthology
> 2019-10-11T07:59:21.957 INFO:teuthology.orchestra.run.target192168000080:Running: 'sudo salt-run rebuild.node target192168000080.teuthology 2>/dev/null'
> 2019-10-11T07:59:53.694 INFO:teuthology.orchestra.run.target192168000080.stdout:The following minions were skipped:
> 2019-10-11T07:59:53.695 INFO:teuthology.orchestra.run.target192168000080.stdout:target192168000080.teuthology
> 2019-10-11T07:59:53.695 INFO:teuthology.orchestra.run.target192168000080.stdout:
> 2019-10-11T07:59:53.695 INFO:teuthology.orchestra.run.target192168000080.stdout:Resolve any issues and run
> 2019-10-11T07:59:53.695 INFO:teuthology.orchestra.run.target192168000080.stdout: salt-run rebuild.nodes target192168000080.teuthology
> ```
> 
> would you have a look @swiftgist or @mgfritch ?

@jschmid1  This regression has no relation to the changes in this PR, but is likely fixed by PR #1786

**Pull request merged**
