### PR TITLE
Correctly parse multiple networks

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <swiftgist@gmail.com>
bsc: 1130511
-----------------

**Checklist:**
- [x] Added unittests and or functional tests
- [ ] Adapted documentation
- [x] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by swiftgist** [comment]
@susebot run teuthology"

**Comment by jschmid1** [comment]
waiting to see if this PR resolves the issue for the user before we merge, k?

**Comment by jan--f** [comment]
ping @AvengerMoJo any thoughts on this?

**Comment by swiftgist** [comment]
Related bug closed with PTF.

**Pull request merged**
