### PR TITLE
Added docs to status, deploy, and undeploy functions

### PR DESCRIPTION
**Pull request by rjfd**
Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by swiftgist** [comment]
@rjfd Has service.status worked for you?  There's a condition in which service.status did not behave.  It's the reason I made the runner cephprocesses instead of cephservices.  With respect to the undeploy/service.stop, wouldn't you want to stop individual gateways? Also, undeploy makes me think the service will be removed.

**Comment by rjfd** [comment]
@swiftgist yes `service.status` has been working for me. What is the condition in which service.status is not behaving for you?

This PR only adds documentation to functions that are already in the master branch. I'm going to close this PR and open it against master.

**Comment by BlaineEXE** [comment]
I agree with @swiftgist that the word "undeploy" isn't particularly telling of what is intended to happen to the system? I think a bit more clarity should be added. What actually happens during a (un-)deployment, e.g., package install, service enable, service start?

**Comment by rjfd** [comment]
@swiftgist @BlaineEXE I agree that `undeploy/deploy` was a bad choice of names, but this should have been caught in the previous PR #223 where I actually added these functions.
Also, I'm already using these function in openATTIC.

I can create a new PR to change these names, and also change in openATTIC PRs. Do you have a good suggestion?

Just a bit of context: the purpose of these functions is to start and stop the iSCSI targets that are configured from openATTIC UI.

**Comment by swiftgist** [comment]
We can carry the conversation in another issue or list.  I did not look as closely at PR #223 since I knew you were adding functionality for oA.

**Pull request merged**
