### PR TITLE
backporting iteration #2

### PR DESCRIPTION
**Pull request by jschmid1**
backporting to stable branch. See changelog for inclusions.

### CODE REVIEW

**Comment by smithfarm** [comment]
@jschmid1 Does this PR need to have the fix for the 'ceph.packages.remove' issue, too? Elsewhere you mentioned it's included in 0.8 but the product is still on 0.7.35 afaict.

**Comment by jschmid1** [comment]
@smithfarm Yes, it's included in 0.8 which I though he shipped in the first place.

The fix we are talking about is in https://github.com/SUSE/DeepSea/commit/c8af8e0db32ebd1ef7db7ddbd63933951b911c2e which is included in the SES5 branch and already staged for maintenance

**Comment by jschmid1** [comment]
good observation, but we discussed this PR already. 

#780 is merged now.

**Comment by carltonf** [comment]
@jschmid1 I note that in this MU preparation, #776 is not included. It still affects cases like bsc#1066502.

**Comment by jecluis** [comment]
Folks, this is a public - upstream - repository. Talking about Maintenance Updates and referring internal bugzilla tickets that are way behind a required login and proper permissions is not cool.
I fully understand that we keep thinking about SUSE/DeepSea as something we only consume, but, please, let's pretend it's not and interact with it as if other people were consuming this project.

**Comment by jschmid1** [comment]
@carltonf This is preparation PR which is still in progress. #776 i.e. has the 'backport' flag, which means that it will eventually be backported to the 'stable' branch. Due to the lack of time, I was not able to proceed with this task yet.

**Comment by carltonf** [comment]
@jschmid1 Oh, thanks for the explanation. I didn't notice it and thought it got lost for all these works.

@jecluis Sure, you are right about that.

**Comment by jschmid1** [comment]
closing, backporting each PR separately

**Pull request closed without merging**
