### PR TITLE
By default teardown apparmor

### PR DESCRIPTION
**Pull request by jan--f**
SLE15 brings apparmor by default. Tear that down in a default installation.

### CODE REVIEW

**Comment by Martin-Weiss** [comment]
Stage.3 does not run with apparmor enabled and running. Stopping apparmor via systemd does not do teardown.

Martin

**Comment by jan--f** [comment]
> I assume everything breaks by default if we don't do this?

Thats right.

**Comment by jan--f** [comment]
> Stage.3 does not run with apparmor enabled and running. Stopping apparmor via systemd does not do teardown. Martin

Hence the `aa-teardown` command.

**Comment by jschmid1** [comment]
@susebot run teuthology

**Pull request merged**
