### PR TITLE
cli: run stage parsing phase as "salt" user

### PR DESCRIPTION
**Pull request by rjfd**
Some runners are executed during jinja evaluation of SLS files. If these runners have side-effects such has create/modify a file in the filesystem, the file is created with the current process user as the owner.

When running the stages with the `salt-run`command, Salt will execute the runners with the "salt" user. Therefore, deepsea-cli must also run the stage parsing phase with the "salt" user.

Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
Doesn't seem to stop the "permission denied":

```
2017-09-21T17:40:18.846 INFO:teuthology.orchestra.run.target149202163079.stderr:+ deepsea --log-file=/var/log/salt/deepsea.log --log-level=debug stage run ceph.stage.4 --simple-output
2017-09-21T17:40:18.846 INFO:teuthology.orchestra.run.target149202163079.stdout:
2017-09-21T17:40:18.846 INFO:teuthology.orchestra.run.target149202163079.stdout:*********************************************
2017-09-21T17:40:18.846 INFO:teuthology.orchestra.run.target149202163079.stdout:********** Running DeepSea Stage 4 **********
2017-09-21T17:40:18.847 INFO:teuthology.orchestra.run.target149202163079.stdout:*********************************************
2017-09-21T17:40:18.847 INFO:teuthology.orchestra.run.target149202163079.stdout:using DeepSea CLI
2017-09-21T17:40:19.108 INFO:teuthology.orchestra.run.target149202163079.stdout:Starting stage: ceph.stage.4
2017-09-21T17:42:04.800 INFO:teuthology.orchestra.run.target149202163079.stdout:Parsing stage ceph.stage.4 steps... done
2017-09-21T17:42:04.801 INFO:teuthology.orchestra.run.target149202163079.stdout:
2017-09-21T17:42:04.802 INFO:teuthology.orchestra.run.target149202163079.stdout:Stage initialization output:
2017-09-21T17:42:04.802 INFO:teuthology.orchestra.run.target149202163079.stdout:openattic                : [1m[92mvalid[0m
2017-09-21T17:42:04.802 INFO:teuthology.orchestra.run.target149202163079.stdout:
2017-09-21T17:42:04.803 INFO:teuthology.orchestra.run.target149202163079.stdout:[init] Executing runner validate.deploy... ok
2017-09-21T17:42:04.803 INFO:teuthology.orchestra.run.target149202163079.stdout:[init] Executing runner select.minions... ok
2017-09-21T17:42:04.803 INFO:teuthology.orchestra.run.target149202163079.stdout:[init] Executing runner select.minions... ok
2017-09-21T17:42:04.803 INFO:teuthology.orchestra.run.target149202163079.stdout:[init] Executing runner select.minions... ok
2017-09-21T17:42:04.804 INFO:teuthology.orchestra.run.target149202163079.stdout:[init] Executing runner changed.config... fail
2017-09-21T17:42:04.804 INFO:teuthology.orchestra.run.target149202163079.stdout:[init] Executing runner select.minions... ok
2017-09-21T17:42:04.804 INFO:teuthology.orchestra.run.target149202163079.stdout:[init] Executing runner select.minions... ok
2017-09-21T17:42:04.804 INFO:teuthology.orchestra.run.target149202163079.stdout:
2017-09-21T17:42:04.805 INFO:teuthology.orchestra.run.target149202163079.stdout:[1/9] Executing state ceph.mds.pools...
2017-09-21T17:42:04.805 INFO:teuthology.orchestra.run.target149202163079.stdout:         |_  select.minions(cluster=ceph, roles=mds)... ok
2017-09-21T17:42:04.805 INFO:teuthology.orchestra.run.target149202163079.stdout:         target149202163079.teuthology... ok
2017-09-21T17:42:04.805 INFO:teuthology.orchestra.run.target149202163079.stdout:[2/9] Executing state ceph.mds.auth...
2017-09-21T17:42:04.806 INFO:teuthology.orchestra.run.target149202163079.stdout:         |_  select.minions(cluster=ceph, host=True, roles=mds)... ok
2017-09-21T17:42:04.806 INFO:teuthology.orchestra.run.target149202163079.stdout:         target149202163079.teuthology... ok
2017-09-21T17:42:04.806 INFO:teuthology.orchestra.run.target149202163079.stdout:[3/9] Executing state ceph.mds...
2017-09-21T17:42:04.806 INFO:teuthology.orchestra.run.target149202163079.stdout:         |_  target149202163072.teuthology: /var/lib/ceph/mds/ceph-target149202163072/keyring ok
2017-09-21T17:42:04.807 INFO:teuthology.orchestra.run.target149202163079.stdout:         target149202163072.teuthology... ok
2017-09-21T17:42:04.807 INFO:teuthology.orchestra.run.target149202163079.stdout:[4/9] Executing state ceph.rgw.auth...
2017-09-21T17:42:04.807 INFO:teuthology.orchestra.run.target149202163079.stdout:         |_  select.minions(cluster=ceph, host=True, roles=rgw)... ok
2017-09-21T17:42:04.807 INFO:teuthology.orchestra.run.target149202163079.stdout:         target149202163079.teuthology... ok
2017-09-21T17:42:04.808 INFO:teuthology.orchestra.run.target149202163079.stdout:[5/9] Executing state ceph.rgw.users...
2017-09-21T17:42:04.808 INFO:teuthology.orchestra.run.target149202163079.stdout:         target149202163079.teuthology... ok
2017-09-21T17:42:04.808 INFO:teuthology.orchestra.run.target149202163079.stdout:[6/9] Executing state ceph.rgw...
2017-09-21T17:42:04.809 INFO:teuthology.orchestra.run.target149202163079.stdout:         |_  target149202163072.teuthology: /var/lib/ceph/radosgw/ceph-rgw.target149202163072/keyring ok
2017-09-21T17:42:04.809 INFO:teuthology.orchestra.run.target149202163079.stdout:         target149202163072.teuthology... ok
2017-09-21T17:42:04.809 INFO:teuthology.orchestra.run.target149202163079.stdout:[7/9] Executing state ceph.ganesha.auth...
2017-09-21T17:42:04.810 INFO:teuthology.orchestra.run.target149202163079.stdout:         |_  select.minions(cluster=ceph, host=True, roles=ganesha)... ok
2017-09-21T17:42:04.810 INFO:teuthology.orchestra.run.target149202163079.stdout:         target149202163079.teuthology... ok
2017-09-21T17:42:04.810 INFO:teuthology.orchestra.run.target149202163079.stdout:[8/9] Executing state ceph.ganesha.config...
2017-09-21T17:42:04.810 INFO:teuthology.orchestra.run.target149202163079.stdout:         |_  select.minions(cluster=ceph, host=True, roles=ganesha)... ok
2017-09-21T17:42:04.811 INFO:teuthology.orchestra.run.target149202163079.stdout:         |_  select.minions(cluster=ceph, roles=mds)... ok
2017-09-21T17:42:04.811 INFO:teuthology.orchestra.run.target149202163079.stdout:         |_  select.minions(cluster=ceph, roles=rgw)... ok
2017-09-21T17:42:04.811 INFO:teuthology.orchestra.run.target149202163079.stdout:         |_  target149202163079.teuthology: /srv/salt/ceph/ganesha/cache/ganesha.target149202163072.conf ok
2017-09-21T17:42:04.811 INFO:teuthology.orchestra.run.target149202163079.stdout:         target149202163079.teuthology... ok
2017-09-21T17:42:04.812 INFO:teuthology.orchestra.run.target149202163079.stdout:[9/9] Executing state ceph.ganesha...
2017-09-21T17:42:04.812 INFO:teuthology.orchestra.run.target149202163079.stdout:         |_  target149202163072.teuthology: /var/lib/ceph/radosgw/ceph-ganesha.target149202163072/keyring ok
2017-09-21T17:42:04.812 INFO:teuthology.orchestra.run.target149202163079.stdout:         target149202163072.teuthology... ok
2017-09-21T17:42:04.812 INFO:teuthology.orchestra.run.target149202163079.stdout:Finished stage ceph.stage.4: succeeded=8/9 failed=1/9
2017-09-21T17:42:04.813 INFO:teuthology.orchestra.run.target149202163079.stdout:
2017-09-21T17:42:04.813 INFO:teuthology.orchestra.run.target149202163079.stdout:Failures summary:
2017-09-21T17:42:04.813 INFO:teuthology.orchestra.run.target149202163079.stdout:changed.config (/srv/modules/runners/changed.py):
2017-09-21T17:42:04.813 INFO:teuthology.orchestra.run.target149202163079.stdout:  Exception occurred in runner changed.config: Traceback (most recent call last):
2017-09-21T17:42:04.813 INFO:teuthology.orchestra.run.target149202163079.stdout:    File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
2017-09-21T17:42:04.814 INFO:teuthology.orchestra.run.target149202163079.stdout:      data['return'] = self.functions[fun](*args, **kwargs)
2017-09-21T17:42:04.814 INFO:teuthology.orchestra.run.target149202163079.stdout:    File "/srv/modules/runners/changed.py", line 154, in config
2017-09-21T17:42:04.814 INFO:teuthology.orchestra.run.target149202163079.stdout:      return requires_conf_change(service)
2017-09-21T17:42:04.814 INFO:teuthology.orchestra.run.target149202163079.stdout:    File "/srv/modules/runners/changed.py", line 131, in requires_conf_change
2017-09-21T17:42:04.815 INFO:teuthology.orchestra.run.target149202163079.stdout:      if Config(deps).has_change():
2017-09-21T17:42:04.815 INFO:teuthology.orchestra.run.target149202163079.stdout:    File "/srv/modules/runners/changed.py", line 119, in has_change
2017-09-21T17:42:04.815 INFO:teuthology.orchestra.run.target149202163079.stdout:      self.write_checksum(current_cs)
2017-09-21T17:42:04.815 INFO:teuthology.orchestra.run.target149202163079.stdout:    File "/srv/modules/runners/changed.py", line 89, in write_checksum
2017-09-21T17:42:04.816 INFO:teuthology.orchestra.run.target149202163079.stdout:      with open(self.checksum_file, 'w') as fd:
2017-09-21T17:42:04.816 INFO:teuthology.orchestra.run.target149202163079.stdout:  IOError: [Errno 13] Permission denied: '/srv/salt/ceph/configuration/files/ceph.conf.checksum/rgw.conf'
```

**Comment by smithfarm** [comment]
Doesn't seem to stop the "permission denied", but the ganesha+rgw Stage 4 error-handling is much improved :-)

**Comment by rjfd** [comment]
@smithfarm this is strange, the parsing is now executing as the "salt" user. Is it possible to know who is the owner of that file?

**Comment by smithfarm** [comment]
Ah, the "permission denied" event is emitted in the non-CLI version of the test, too, so it's not a problem with the CLI:

`17-09-21T17:39:59.793 INFO:teuthology.orchestra.run.target149202164133.stdout:[DEBUG   ] Sending event: tag = salt/run/20170921173958639556/ret; data = {'fun_args': [{'service': 'rgw'}], 'jid': '20170921173958639556', 'return': 'Exception occurred in runner changed.config: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\n  File "/srv/modules/runners/changed.py", line 154, in config\n    return requires_conf_change(service)\n  File "/srv/modules/runners/changed.py", line 131, in requires_conf_change\n    if Config(deps).has_change():\n  File "/srv/modules/runners/changed.py", line 119, in has_change\n    self.write_checksum(current_cs)\n  File "/srv/modules/runners/changed.py", line 89, in write_checksum\n    with open(self.checksum_file, \'w\') as fd:\nIOError: [Errno 13] Permission denied: \'/srv/salt/ceph/configuration/files/ceph.conf.checksum/rgw.conf\'\n', 'success': False, '_stamp': '2017-09-21T17:39:59.777625', 'user': 'UNKNOWN', 'fun': 'runner.changed.config'}`

**Comment by smithfarm** [comment]
It appears that `make install` installs stuff as root and does not chown to salt:

```
wilbur:/home/smithfarm/src/DeepSea # ls -l /srv/salt/ceph/configuration/files/
total 24
-rw-r--r-- 1 root root  888 Sep 21 22:04 ceph.conf-shared.j2
drw-r--r-- 1 salt salt    0 Sep 21 22:04 ceph.conf.checksum
drwxr-xr-x 1 root root   12 Sep 21 22:04 ceph.conf.d
-rw-r--r-- 1 salt salt   93 Sep 21 22:04 ceph.conf.import
-rw-r--r-- 1 root root 2016 Sep 21 22:04 ceph.conf.j2
-rw-r--r-- 1 root root   25 Sep 21 22:04 rbd.conf
-rw-r--r-- 1 root root  119 Sep 21 22:04 rgw-ssl.conf
-rw-r--r-- 1 root root   83 Sep 21 22:04 rgw.conf
```

**Comment by smithfarm** [comment]
The directory is owned by root, so `salt` cannot create or modify anything inside it:

```
# ls -ld /srv/salt/ceph/configuration/files/
drwxr-xr-x 1 root root 208 Sep 21 22:04 /srv/salt/ceph/configuration/files/
```

**Comment by smithfarm** [comment]
Opened https://github.com/SUSE/DeepSea/issues/675 for the directory ownership issue.

**Comment by rjfd** [comment]
@smithfarm good catch.

Nevertheless this PR still solves a potential problem with permissions :-)

**Comment by rjfd** [comment]
@smithfarm just pushed a change that handles the case when there are parsing errors. Now the parsing exception is sent to the parent process so it can properly be raised.

**Pull request merged**
