### PR TITLE
Use salt's stack.py

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <ejackson@suse.com>
bsc: 1167571

-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [x] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by shyukri** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
retest this please

**Comment by jschmid1** [comment]
jenkins retest this please

**Pull request merged**
