### PR TITLE
[SES6] iscsi: fix iscsi restart before upgrade to ceph-iscsi

### PR DESCRIPTION
**Pull request by rjfd**
Fixes: bsc#1136066

Signed-off-by: Ricardo Dias <rdias@suse.com>
(cherry picked from commit 9fe0d1107a9ba27d05c1bdc76d2df446d1c634b5)

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology suse:tier0

**Comment by kshtsk** [comment]
@susebot run teuthology suse:tier0

**Comment by kshtsk** [comment]
@susebot run teuthology suse:tier0

**Comment by kshtsk** [comment]
@susebot run teuthology suse:tier0

**Comment by jschmid1** [comment]
@susebot run teuthology suse:tier0

**Pull request merged**
