### PR TITLE
Correct pool for condition

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <ejackson@suse.com>
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1178016

-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [x] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
test this please

**Review by smithfarm — APPROVED** [review]

**Comment by smithfarm** [comment]
@jan--f Ping

**Review by jan--f — APPROVED** [review]

**Pull request merged**
