### PR TITLE
Always return an entry from Device Files, if possible

### PR DESCRIPTION
**Pull request by swiftgist**
bsc: 1097532

Signed-off-by: Eric Jackson <ejackson@suse.com>

### CODE REVIEW

**Comment by swiftgist** [comment]
Just a note: `make lint` is succeeding for me locally.

**Comment by kshtsk** [comment]
@swiftgist Try to run 'make lint' in clean environment.

**Comment by swiftgist** [comment]
@kshtsk what error do you get?  I do not see one when I click Details.

**Comment by kshtsk** [comment]
@swiftgist Click at " Console Output"

**Comment by jschmid1** [comment]
Is the description of `_prefer_underscore` actually correct? It states:

`In the worst case, return the last device`. And the function actually does that by returning a `-1` if there is no item with an underscore in the list.
However the invoking method `_device` has:

``` python
if index > -1:
    return devices[index]
return drive['Device File']
```

This logic implies that if there is no drive with an underscore, ( returns -1  and supposedly return the _last_ item ) the conditional does not assert and we drop down to returning the drive['Device File'] which is most of the time the short name. ( or the _first_ item in the drives list )

**Comment by swiftgist** [comment]
This fix was originally to address an issue in the field.  The first device in 'Device Files' is the short name so the last device would often begin with 'scsi-3'.  

If #1222 is accepted, then this PR is not needed.

**Comment by jschmid1** [comment]
Closing in favor of #1222

**Pull request closed without merging**
