### PR TITLE
Enable salt-api

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <ejackson@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
This PR introduced a regression (stage.0 hangs). Reproducibility: 100% (apparently).

Reverting this commit fixes the issue.

**Comment by swiftgist** [comment]
Realized last night while testing openATTIC that most pages were failures due to the salt-api being down.  Thought we had addressed this, but found no reference.

I verified the stage would start the salt-api, but forgot about the salt-master restart.  Not sure how to address that issue at the moment.

**Comment by smithfarm** [comment]
Yeah, in the minion log, I see the salt-master.service getting restarted about 2 seconds after the master emits its last log message and hangs.

**Comment by swiftgist** [comment]
This is reverted in #512 now.  New packages incoming.

**Pull request merged**
