### PR TITLE
cli: fix simple outputter when printing stage exception

### PR DESCRIPTION
**Pull request by rjfd**
Signed-off-by: Ricardo Dias <rdias@suse.com>

Fixes the stack trace shown in this comment:
https://github.com/SUSE/DeepSea/pull/1516#issuecomment-465795371

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by rjfd** [comment]
> Commit bfce558 is NOT OK for suite suse:tier1. 

@jschmid1 where should I look for an error when tests fail?

**Comment by jschmid1** [comment]
@rjfd here http://storage-ci.suse.de:8080/job/pr-deepsea/72/testReport/junit/teuthology/suse_tier1/health_ok__0_salt_yaml_1_deploy_phase_yaml_2_test_phase_yaml_boilerplate__ceph_cm_salt_yaml_disable_tuned_yaml_zypper_dup_yaml__cluster__4disks_yaml_roles_yaml__deepsea_cli_off_yaml_distros_sle_15_1_yaml_/attachments/teuthology-10995.log

However it looks like the CLI is currently disabled for master. @smithfarm has to take care of enabling it again.

Besides that it doesn't look like your change is the cause for this failure.

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
I think the following journalctl excerpt is relevant to the above failure:

```
2019-03-19T13:26:34.149 INFO:teuthology.orchestra.run.target192168000029.stdout:Mar 19 13:26:23 target192168000029.teuthology salt-minion[3107]: [INFO    ] Running state [cephprocesses.wait] at time 13:26:23.252599
2019-03-19T13:26:34.149 INFO:teuthology.orchestra.run.target192168000029.stdout:Mar 19 13:26:23 target192168000029.teuthology salt-minion[3107]: [INFO    ] Executing state module.run for [cephprocesses.wait]
2019-03-19T13:26:34.149 INFO:teuthology.orchestra.run.target192168000029.stdout:Mar 19 13:26:23 target192168000029.teuthology salt-minion[3107]: [WARNING ] The function "module.run" is using its deprecated version and will expire in version "Sodium".
2019-03-19T13:26:34.149 INFO:teuthology.orchestra.run.target192168000029.stdout:Mar 19 13:26:23 target192168000029.teuthology salt-minion[3107]: [ERROR   ] ERROR: process ceph-mgr for role mgr is not running
2019-03-19T13:26:34.149 INFO:teuthology.orchestra.run.target192168000029.stdout:Mar 19 13:26:23 target192168000029.teuthology salt-master[4317]: [INFO    ] Got return from target192168000029.teuthology for job 20190319132623069279
2019-03-19T13:26:34.149 INFO:teuthology.orchestra.run.target192168000029.stdout:Mar 19 13:26:23 target192168000029.teuthology salt-master[4317]: [DEBUG   ] Sending event: tag = salt/job/20190319132623069279/ret/target192168000029.teuthology; data = {'cmd': '_return', 'id': 'target192168000029.teuthology', 'success': True, 'return': {'pid': 32607, 'fun': 'state.sls', 'arg': ['ceph.mgr', {'__kwarg__': True, 'queue': False, 'concurrent': False}], 'tgt': 'I@roles:mgr and I@cluster:ceph', 'jid': '20190319132557821893', 'ret': '', 'tgt_type': 'compound', 'user': 'salt'}, 'retcode': 0, 'jid': '20190319132623069279', 'fun': 'saltutil.find_job', 'fun_args': ['20190319132557821893'], '_stamp': '2019-03-19T13:26:23.915304'}
2019-03-19T13:26:34.150 INFO:teuthology.orchestra.run.target192168000029.stdout:Mar 19 13:26:23 target192168000029.teuthology salt-master[4317]: [DEBUG   ] Gathering reactors for tag salt/job/20190319132623069279/ret/target192168000029.teuthology
2019-03-19T13:26:34.150 INFO:teuthology.orchestra.run.target192168000029.stdout:Mar 19 13:26:23 target192168000029.teuthology salt-minion[3107]: [DEBUG   ] Closing AsyncZeroMQReqChannel instance
2019-03-19T13:26:34.150 INFO:teuthology.orchestra.run.target192168000029.stdout:Mar 19 13:26:23 target192168000029.teuthology salt-minion[3107]: [DEBUG   ] minion return: {'success': True, 'return': {'pid': 32607, 'fun': 'state.sls', 'arg': ['ceph.mgr', {'__kwarg__': True, 'queue': False, 'concurrent': False}], 'tgt': 'I@roles:mgr and I@cluster:ceph', 'jid': '20190319132557821893', 'ret': '', 'tgt_type': 'compound', 'user': 'salt'}, 'retcode': 0, 'jid': '20190319132623069279', 'fun': 'saltutil.find_job', 'fun_args': ['20190319132557821893']}
2019-03-19T13:26:34.150 INFO:teuthology.orchestra.run.target192168000029.stdout:Mar 19 13:26:25 target192168000029.teuthology salt-minion[3107]: [ERROR   ] ERROR: process ceph-mgr for role mgr is not running
2019-03-19T13:26:34.150 INFO:teuthology.orchestra.run.target192168000029.stdout:Mar 19 13:26:29 target192168000029.teuthology salt-minion[3107]: [ERROR   ] Timeout expired
2019-03-19T13:26:34.150 INFO:teuthology.orchestra.run.target192168000029.stdout:Mar 19 13:26:29 target192168000029.teuthology salt-minion[3107]: [ERROR   ] {'ret': False}
2019-03-19T13:26:34.150 INFO:teuthology.orchestra.run.target192168000029.stdout:Mar 19 13:26:29 target192168000029.teuthology salt-minion[3107]: [INFO    ] Completed state [cephprocesses.wait] at time 13:26:29.367075 (duration_in_ms=6114.475)
```

@tserong would know more about this, but ISTR that the ceph-mgr process needs to bring up all its modules when it starts, and this can take some time. DeepSea should wait longer - `cephprocesses.wait` seems to be timing out too early here?

**Comment by smithfarm** [comment]
Functional tests (CLI, non-CLI) running here: http://10.86.0.53:8081/ubuntu-2019-03-20_10:51:49-suse:tier1-ses6---basic-openstack/

**Comment by smithfarm** [comment]
@jschmid1 Do you understand this failure? Looks like something is missing in the `deepsea-qa` RPM for the functests to work?

```
2019-03-20T11:16:49.672 INFO:tasks.deepsea.orch:WWWW: running orchestration ceph.functests.1node
2019-03-20T11:16:49.675 INFO:teuthology.orchestra.run.target192168000057:Running: "sudo bash -c 'DEV_ENV=true timeout 60m salt-run --no-color state.orch ceph.functests.1node 2>/dev/null'"
2019-03-20T11:17:04.731 INFO:teuthology.orchestra.run.target192168000057.stdout:target192168000057.teuthology_master:
2019-03-20T11:17:04.732 INFO:teuthology.orchestra.run.target192168000057.stdout:    Data failed to compile:
2019-03-20T11:17:04.732 INFO:teuthology.orchestra.run.target192168000057.stdout:----------
2019-03-20T11:17:04.732 INFO:teuthology.orchestra.run.target192168000057.stdout:    Specified SLS ceph.functests.1node.symlink in saltenv base is not available on the salt master or through a configured fileserver
2019-03-20T11:17:04.894 ERROR:tasks.deepsea.orch:orchestration ceph.functests.1node failed. Here comes journalctl!
```

**Comment by smithfarm** [comment]
OK, I grabbed the `deepsea-qa` RPM that is being built and used by the CI, and it is missing `/srv/salt/ceph/functests/1node/symlink` entirely, which would appear to be a bug in how the PR CI is building the RPM.

**Comment by smithfarm** [comment]
The CI failure is indeed a regression - should be fixed by #1577 
We could try running teuthology again after that PR merges.

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
The failures look to be caused by a transient network connectivity issue in the RPM building phase.

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
The failure is transient, tracked by https://github.com/SUSE/DeepSea/issues/1580

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
Sigh. Testing is currently blocked by #1580

**Comment by tserong** [comment]
> @tserong would know more about this, but ISTR that the ceph-mgr process needs to bring up all its modules when it starts, and this can take some time. DeepSea should wait longer - `cephprocesses.wait` seems to be timing out too early here? (Looks like it's using a timeout of 5 seconds?)

Well, yeah, ceph-mgr takes a certain amount of time to load all its modules, but still, cephprocesses.wait is just waiting until ceph-mgr is in the list of running processes, and it should appear there reasonably quickly, even if it takes a bit longer for the modules to load.  Is it worth increasing the timeout?

**Comment by smithfarm** [comment]
> Is it worth increasing the timeout?

Probably not? (The Jenkins logs from that earlier failure are gone already, and in the meantime it stopped happening...)

**Comment by tserong** [comment]
OK, let's leave it as-is.

**Pull request merged**
