### PR TITLE
ganesha: upgrade orchestration

### PR DESCRIPTION
**Pull request by rjfd**
This PR adds the orchestration for upgrading NFS-Ganesha. The upgrade orchestration is part of the ganesha service orchestration, which in turn is part of stage 4.

### CODE REVIEW

**Comment by jschmid1** [comment]
Unittests and-or functests would be lovely :>

**Comment by rjfd** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
```
2019-05-03T16:25:15.113 INFO:teuthology.orchestra.run.target192168000057.stdout:Failures summary:
2019-05-03T16:25:15.113 INFO:teuthology.orchestra.run.target192168000057.stdout:ganesha_upgrade.validate (/srv/modules/runners/ganesha_upgrade.py):
2019-05-03T16:25:15.113 INFO:teuthology.orchestra.run.target192168000057.stdout:  Failed to run pkg.info_installed in ganesha minions
```
from the logs

**Comment by rjfd** [comment]
closing this in favor of #1640

**Pull request closed without merging**
