### PR TITLE
Add osd/partition to spec and makefile

### PR DESCRIPTION
**Pull request by supriti**
Signed-off-by: Supriti Singh <supriti.singh@suse.com>

### CODE REVIEW

**Comment by jschmid1** [comment]
Shouldn't the osd/partition (and possibly more) be deprecated in favor of the new osd.py module?

**Comment by supriti** [comment]
I was trying to setup a "default-small" cluster, and it complained about missing ceph.osd.partition. In file, https://github.com/SUSE/DeepSea/blob/master/srv/salt/ceph/osd/default-small.sls we are including partition. I am not aware of osd.py module, so could be we just missed out updating it in default-small.sls.

**Comment by swiftgist** [comment]
We need to remove default-small.sls.  I missed that while cleaning up.  The default.sls now calls osd.deploy which handles drives under 10G too.

**Comment by supriti** [comment]
@swiftgist Okay. I was not aware of osd.deploy handling the case.  I will close this PR then. Wiki also need to updated accordingly(https://github.com/SUSE/DeepSea/wiki/override)

**Pull request closed without merging**
