### PR TITLE
Fix subvolume mount for generic device or label

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <ejackson@suse.com>
bnc:#1139379
-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [x] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
Having the `awk` expr inside the .sls files makes it really hard to verify if it's correct. Could we offload this to a module and have this unit-tested?

**Comment by swiftgist** [comment]
I added a function, but I did think it was overkill for "print first column for the root filesystem when it's btrfs".

**Comment by jschmid1** [comment]
> I added a function, but I did think it was overkill for "print first column for the root filesystem when it's btrfs".

Reads may better, imo. Thanks!

**Comment by jschmid1** [comment]
We received a request to include this in SES6. Would you mind creating a backport of this @swiftgist ?

**Comment by swiftgist** [comment]
It's already there in commit e673363dfca4707b2a704a98622fddefa6c48dd3

**Pull request merged**
