### PR TITLE
qa: make 1- and 2-node clusters reach HEALTH_OK

### PR DESCRIPTION
**Pull request by smithfarm**
For the time being we're introducing a `qa/.config` (which must be populated for each run) to tell the integration testing script how many storage nodes there are. If the number is less than three, then the necessary ceph.conf knobs are twiddled to ensure the cluster reaches HEALTH_OK.

No longer tolerate HEALTH_WARN.

Use "wait.until status=HEALTH_OK" to give the cluster some time to reach HEALTH_OK. The timeout seems to be five minutes. Don't know could that be extended, but it seems to reach HEALTH_OK pretty quick, so perhaps 5 minutes is enough.

### CODE REVIEW

**Comment by smithfarm** [comment]
I have a gnawing feeling that this `qa/.config` thing is ill-conceived, or at least overkill for determining the number of storage nodes. Each script already knows whether it calls for a client node. The number of storage nodes is simply: total_number_of_nodes minus number_of_client_nodes (where the latter can be either 0 or 1).

But I have a feeling that `qa/.config` may turn out to be useful down the road, so we might as well have the infrastructure. What does anyone think?

What is the most elegant way of determining the total number of nodes/minions?

**Comment by smithfarm** [comment]
How about this proposal. Some tests may be able to take advantage of multiple client nodes, yet not *require* any particular number of client nodes. That would be a use case for `qa/.config` with the following structure:

```
TOTALNODES=5
STORAGENODES=3
CLIENTNODES=2
```

**Comment by smithfarm** [comment]
This passes `deepsea/basic` in teuthology, which currently consists of four tests:

* minimal HEALTH_OK test on 1 node, 2 nodes, and 3 nodes
* minimal MDS health test on 3 nodes

**Comment by rjfd** [comment]
@smithfarm why do we need the the contents of the `.config` file? Couldn't we find out automatically the resources available?

**Comment by smithfarm** [comment]
@rjfd I'm not sure we need it. The immediate problem it is solving is this: if there are less than three storage nodes, I have to apply special settings to `ceph.conf`. Assuming that the custom configuration settings are only applied in Stage 3, after Stage 2 I could query the roles to find out how many storage nodes there are. However, I would also like to set DEV_ENV to true if there are enough storage nodes and MONs. And I'm assuming DEV_ENV needs to get set at the very beginning of the script, i.e. before Stage 0.

**Comment by rjfd** [comment]
@smithfarm DEV_ENV is only used in stage 3

**Comment by smithfarm** [comment]
OK, on the assumption that we don't need any of this information until Stage 3, I'm implementing functions that use salt to count the total number of nodes, total number of nodes with storage role, etc. No need for a configuration file, at least for now.

**Comment by jan--f** [comment]
I think its  a good idea to pass the aimed-for environment like this. Its portable, as-in work in teuthology and when running the script manually. It ultimately allows us to run tests with customized cluster layouts, i.e. a tester can influence policy.cfg (or in Teuthology we can pass what is specified in suite's config).
We could adjust the script to set defaults should the .config file not be present to allow simple runs without setting an explicit config.

I'd be in favour of making it a non-hodden file though. If the file would somehwo stay behind and influence a test run, a hidden file might not be very obvious, making it a bit of a magic file.

**Comment by rjfd** [comment]
> It ultimately allows us to run tests with customized cluster layouts, i.e. a tester can influence policy.cfg (or in Teuthology we can pass what is specified in suite's config).

That's a good point, although in this case I would prefer a different format for the `.config` file.
Instead of just specifying the number of storage/client nodes, I think it would be preferable to explicitly enumerate the hostnames for storage/client nodes.

**Comment by smithfarm** [comment]
The config file is turning into a bit of a rabbit hole. Since I've already implemented a workaround, I'm dropping it from this PR and we can revisit it later when it's really needed.

**Comment by rjfd** [comment]
@smithfarm sounds good

**Comment by smithfarm** [comment]
OK, this latest version passes `deepsea/basic`.

**Pull request merged**
