### PR TITLE
Adding nfs-ganesha state to Deepsea

### PR DESCRIPTION
**Pull request by supriti**
With this commit,
- "ganesha" role is defined
- nfs-ganesha and other prerequisite package is installed on the minion acting as ganesha server 
- The service is started with correct conf file. 
- Ganesha is not added as part of services for deployment in stage 4 as it still needs some work. 

Its still WIP. It requires at least the following changes to make it complete
- Better error and state handling. The current commit is missing check if service started with success or not. 
- Adding more fields in ceph.conf for better flexibility
- Checking if cephfs is mounted on the server acting as nfs-ganesha server before doing anything else.

### CODE REVIEW

**Comment by supriti** [comment]
@jan--f @kmroz @swiftgist  Can you please review :) Thanks.

**Comment by rjfd** [comment]
@supriti could you organize your commits (squashing) in a way that each commit appears an "atomic" step. For instance, 1) add ganesha role to deepsea; 2) ganesha state formulas; ... n) ganesha: spec and makefile scripts; etc...

That way will be more easy to review, and we'll get a "better" git history

**Comment by supriti** [comment]
@rjfd Thanks for comment. It is bit com

**Comment by supriti** [comment]
Sorry. PR got closed by mistake. @rjfd Thanks for comment. The commits at my forked repo is not very well organised, so it will be a bit difficult to sqaush it into smaller atomic commits like you suggested. Is it okay if I squash it into a single commit message?

**Comment by rjfd** [comment]
@supriti I often run into the same problem. What I usually end up doing is squash everything into a single commit and then I edit the single commit and create the necessary commits with respective pieces.
The command `git add -p file` is very useful to just add part of the changes of a file for staging.

This is a nice exercise to learn more about git, at least this was how I learned :-), try the "commit edit" in another branch first before doing it in this branch.

**Comment by kmroz** [comment]
@supriti - I agree with @rjfd.  It's a great exercise, and going with the approach of squashing into one commit and then cutting up into smaller, well organized commits is fairly painless.  To be on the safe side, you can always create a branch from your current working branch and do the edits there.  That way if anything goes wrong, you have your original to go back to.

If you're comfortable with emacs, "magit" is a great tool for squashing, performing interactive rebases, etc.

I also like `git gui`.  Once you have your one base commit, you can use `gut gui` to cut it up as you like (chunk or even line level :smile:)  OK, I really like `git gui`!

**Comment by swiftgist** [comment]
I'm fairly neutral on the commit messages for the newest features.  But I do have some questions. :)  

You changed the role from nfs-ganesha to ganesha.  Will ganesha handle both backends simultaneously?  If a customer has both backends (i.e. mds and rgw) how would those gateways be targetted separately.

In the .../ganesha/configure/default.sls, how is the original configuration generated?  I see /etc/ganesha/ganesha.conf as the source but wouldn't this reside in the Salt tree and possibly be a Jinja file?  BTW, I am completely unfamiliar with this configuration.  So, a mumble chat may be simpler.

**Comment by kmroz** [comment]
@supriti - For the record, @rjfd and I are not trying to be hard on you.  This isn't some twisted initiation :smile:  Adding a bit more organization to the commits in a PR just makes the lives of your reviewers a bit easier (among other things).

**Comment by supriti** [comment]
Thanks for feedback. I completely agree, I should have squashed before creating pull request. I am closing this one, as the history will be a bit mess after all adjustment. I will open a new clean pull request. Hope its okay. 

@swiftgist I will attach a proper documentation regarding nfs-ganesha along with next PR to make it easier to discuss.

**Comment by rjfd** [comment]
@supriti no need to close the PR, use the same so we can track all the comments. It is usual to frequently rebase commits of opened PRs.

No worries :-)

**Comment by supriti** [comment]
I already closed and did rebase. Now I can not reopen any more as "the master branch was force-pushed or recreated".  Creating a new one

**Comment by smithfarm** [comment]
@supriti Next time, instead of adding commits directly to the master branch in your clone, I suggest that you make a "wip" (work in progress) branch first. It should be based on upstream master. 

Then, after you rebase, you just `git push -f` your wip branch to your clone, and the PR will be automagically updated.

I find it beneficial to set up the master branch in my clone to track the upstream master branch, like so:

```
git remote add upstream http://github.com/SUSE/DeepSea
git fetch upstream
git checkout master
git reset --hard upstream/master
git push -u origin master
```

Whenever I need to see what is in the upstream master branch, I merge in the latest upstream changes and re-push master to my clone:

```
git fetch upstream
git checkout master
git merge upstream/master
git push -u origin master
```

After doing this, I am 100% certain that my local master branch is exactly the same as upstream master.

**Comment by supriti** [comment]
Thanks @smithfarm I will keep it in my mind for future. Sorry for all the back and forth on this PR.

**Comment by smithfarm** [comment]
@supriti That's OK - all that back and forth is how we learn new stuff :-)

**Comment by smithfarm** [comment]
Using wip branches has a big advantage: it allows you to work concurrently on more than one PR.

**Pull request closed without merging**
