### PR TITLE
Ensure /etc/ceph/ceph.client.admin.keyring matches the actual admin keyring caps

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: #468
Fixes: #476

### CODE REVIEW

**Comment by smithfarm** [comment]
Can you help me here? I'm trying to get it to rewrite `/etc/ceph/ceph.client.admin.keyring` with the output of `ceph auth export client.admin` . . . but something is missing.

**Comment by smithfarm** [comment]
The problem I'm trying to solve is #476 - i.e., the *actual* `client.admin` (admin keyring) caps come from `srv/salt/ceph/mon/files/keyring.j2` and up until this PR those were different from what we are putting in `/etc/ceph/ceph.client.admin.keyring`.

**Comment by tserong** [comment]
I assume we got into this problem in the first place because the mgr caps were updated correctly in srv/salt/ceph/admin/files/keyring.j2 by b39872d, but not in srv/salt/ceph/mon/files/keyring.j2, and the latter will have been what got pulled in by the mons during initial deployment?

The simplest fix for this is probably just to fix the caps in srv/salt/ceph/mon/files/keyring.j2, rather than also later exporting the keyring -- I WTF'd a couple of times at that convolution ;-) -- OTOH, doing that does mean there's only one authoritative place the admin key caps are set now (srv/salt/ceph/mon/files/keyring.j2)...

**Comment by smithfarm** [comment]
@tserong Got it - the idea to export the keyring at the end of stage 3 has been voted down.

**Comment by smithfarm** [comment]
Passes DS suite:

* http://147.135.133.225:8081/ubuntu-2017-07-20_09:17:00-deepsea:basic-ses5---basic-openstack
* http://147.135.133.225:8081/ubuntu-2017-07-20_09:50:58-deepsea-ses5---basic-openstack

**Pull request merged**
