### PR TITLE
configuration: add RBD specific configuration template

### PR DESCRIPTION
**Pull request by rjfd**
Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by swiftgist** [comment]
Is rbd default features = 3 still necessary?

**Comment by rjfd** [comment]
@swiftgist Nothing has changed in kRBD and therefore if we remove the ` rbd default features = 3` the kernel client will be unable to mount the images

**Comment by swiftgist** [comment]
With ceph.conf.d, I think the intention is that these would always be user files and DeepSea wouldn't own anything there other than the README.  

Would it be better to move the rbd.conf up one level and add it to the Makefile/spec file?  In the long term, should the global section be segregated into several files and ceph.conf.j2 is simply includes?

**Comment by swiftgist** [comment]
Never mind me.  Apparently, that eye checkup yesterday did no good. :)

**Pull request merged**
