### PR TITLE
[SES5] Make engulf a bit more user friendly

### PR DESCRIPTION
**Pull request by tserong**
These are the pieces of #1387 which make sense to backport to SES5.

ref: #bsc1108495

### CODE REVIEW

**Comment by jschmid1** [comment]
We should only merge this when it's origin-> #1387  is merged too

**Comment by smithfarm** [comment]
@tserong Needs rebase (suddenly, it has lots of commits. . .)

**Comment by tserong** [comment]
@smithfarm, yep, very much needs rebase, and I also need to rejig some "cherry picked from" lines. I'll redo it once #1387 is in.

**Comment by jschmid1** [comment]
#1387 is in. Ready to rebase

**Comment by tserong** [comment]
Done, finally (I also ended up pulling in the functest)

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
This is an actual failure in the functests:

```

2018-10-10T08:13:28.327 INFO:teuthology.orchestra.run.target158069066084.stdout:  Name: populate.engulf_existing_cluster - Function: salt.runner - Result: Changed Started: - 08:13:05.062820 Duration: 17936.833 ms
2018-10-10T08:13:28.327 INFO:teuthology.orchestra.run.target158069066084.stdout:----------
2018-10-10T08:13:28.327 INFO:teuthology.orchestra.run.target158069066084.stdout:          ID: verify storage profiles
2018-10-10T08:13:28.327 INFO:teuthology.orchestra.run.target158069066084.stdout:    Function: salt.state
2018-10-10T08:13:28.328 INFO:teuthology.orchestra.run.target158069066084.stdout:      Result: False
2018-10-10T08:13:28.328 INFO:teuthology.orchestra.run.target158069066084.stdout:     Comment: Run failed on minions: target158069066084.teuthology
2018-10-10T08:13:28.328 INFO:teuthology.orchestra.run.target158069066084.stdout:              Failures:
2018-10-10T08:13:28.328 INFO:teuthology.orchestra.run.target158069066084.stdout:                  target158069066084.teuthology:
2018-10-10T08:13:28.328 INFO:teuthology.orchestra.run.target158069066084.stdout:                  ----------
2018-10-10T08:13:28.328 INFO:teuthology.orchestra.run.target158069066084.stdout:                            ID: diff -x '\.filter' -ur /srv/pillar/ceph/proposals/profile-default /srv/pillar/ceph/proposals/profile-import
2018-10-10T08:13:28.328 INFO:teuthology.orchestra.run.target158069066084.stdout:                      Function: cmd.run
2018-10-10T08:13:28.329 INFO:teuthology.orchestra.run.target158069066084.stdout:                        Result: False
2018-10-10T08:13:28.329 INFO:teuthology.orchestra.run.target158069066084.stdout:                       Comment: Command "diff -x '\.filter' -ur /srv/pillar/ceph/proposals/profile-default /srv/pillar/ceph/proposals/profile-import" run
2018-10-10T08:13:28.329 INFO:teuthology.orchestra.run.target158069066084.stdout:                       Started: 08:13:23.296231
2018-10-10T08:13:28.329 INFO:teuthology.orchestra.run.target158069066084.stdout:                      Duration: 19.663 ms
2018-10-10T08:13:28.329 INFO:teuthology.orchestra.run.target158069066084.stdout:                       Changes:
2018-10-10T08:13:28.329 INFO:teuthology.orchestra.run.target158069066084.stdout:                                ----------
2018-10-10T08:13:28.329 INFO:teuthology.orchestra.run.target158069066084.stdout:                                pid:
2018-10-10T08:13:28.330 INFO:teuthology.orchestra.run.target158069066084.stdout:                                    48886
2018-10-10T08:13:28.330 INFO:teuthology.orchestra.run.target158069066084.stdout:                                retcode:
2018-10-10T08:13:28.330 INFO:teuthology.orchestra.run.target158069066084.stdout:                                    1
2018-10-10T08:13:28.330 INFO:teuthology.orchestra.run.target158069066084.stdout:                                stderr:
2018-10-10T08:13:28.330 INFO:teuthology.orchestra.run.target158069066084.stdout:                                stdout:
2018-10-10T08:13:28.330 INFO:teuthology.orchestra.run.target158069066084.stdout:                                    diff -x '\.filter' -ur /srv/pillar/ceph/proposals/profile-default/stack/default/ceph/minions/target158069066084.teuthology.yml /srv/pillar/ceph/proposals/profile-import/stack/default/ceph/minions/target158069066084.teuthology.yml
2018-10-10T08:13:28.330 INFO:teuthology.orchestra.run.target158069066084.stdout:                                    --- /srv/pillar/ceph/proposals/profile-default/stack/default/ceph/minions/target158069066084.teuthology.yml	2018-10-10 08:08:10.745294103 +0000
2018-10-10T08:13:28.331 INFO:teuthology.orchestra.run.target158069066084.stdout:                                    +++ /srv/pillar/ceph/proposals/profile-import/stack/default/ceph/minions/target158069066084.teuthology.yml	2018-10-10 08:13:17.404086080 +0000
2018-10-10T08:13:28.331 INFO:teuthology.orchestra.run.target158069066084.stdout:                                    @@ -1,6 +1,10 @@
2018-10-10T08:13:28.331 INFO:teuthology.orchestra.run.target158069066084.stdout:                                     ceph:
2018-10-10T08:13:28.331 INFO:teuthology.orchestra.run.target158069066084.stdout:                                       storage:
2018-10-10T08:13:28.331 INFO:teuthology.orchestra.run.target158069066084.stdout:                                         osds:
2018-10-10T08:13:28.331 INFO:teuthology.orchestra.run.target158069066084.stdout:                                    +      /dev/vdb:
2018-10-10T08:13:28.331 INFO:teuthology.orchestra.run.target158069066084.stdout:                                    +        format: bluestore
2018-10-10T08:13:28.332 INFO:teuthology.orchestra.run.target158069066084.stdout:                                    +      /dev/vdc:
2018-10-10T08:13:28.332 INFO:teuthology.orchestra.run.target158069066084.stdout:                                    +        format: bluestore
2018-10-10T08:13:28.332 INFO:teuthology.orchestra.run.target158069066084.stderr:[DEBUG   ] LazyLoaded local_cache.prep_jid
2018-10-10T08:13:28.333 INFO:teuthology.orchestra.run.target158069066084.stderr:[INFO    ] Runner completed: 20181010080507163039
2018-10-10T08:13:28.333 INFO:teuthology.orchestra.run.target158069066084.stderr:[DEBUG   ] Runner return: {'outputter': 'highstate', 'retcode': 1}
2018-10-10T08:13:28.333 INFO:teuthology.orchestra.run.target158069066084.stdout:                                           /dev/vdd:
2018-10-10T08:13:28.334 INFO:teuthology.orchestra.run.target158069066084.stdout:                                             format: bluestore
2018-10-10T08:13:28.334 INFO:teuthology.orchestra.run.target158069066084.stdout:                                           /dev/vde:
2018-10-10T08:13:28.334 INFO:teuthology.orchestra.run.target158069066084.stdout:
2018-10-10T08:13:28.334 INFO:teuthology.orchestra.run.target158069066084.stdout:                  Summary for target158069066084.teuthology
2018-10-10T08:13:28.334 INFO:teuthology.orchestra.run.target158069066084.stdout:                  ------------
2018-10-10T08:13:28.334 INFO:teuthology.orchestra.run.target158069066084.stdout:                  Succeeded: 0 (changed=1)
2018-10-10T08:13:28.334 INFO:teuthology.orchestra.run.target158069066084.stdout:                  Failed:    1
2018-10-10T08:13:28.335 INFO:teuthology.orchestra.run.target158069066084.stdout:                  ------------
2018-10-10T08:13:28.335 INFO:teuthology.orchestra.run.target158069066084.stdout:                  Total states run:     1
2018-10-10T08:13:28.335 INFO:teuthology.orchestra.run.target158069066084.stdout:                  Total run time:  19.663 ms
2018-10-10T08:13:28.335 INFO:teuthology.orchestra.run.target158069066084.stdout:     Started: 08:13:23.000454
2018-10-10T08:13:28.335 INFO:teuthology.orchestra.run.target158069066084.stdout:    Duration: 331.733 ms
2018-10-10T08:13:28.335 INFO:teuthology.orchestra.run.target158069066084.stdout:     Changes:
2018-10-10T08:13:28.335 INFO:teuthology.orchestra.run.target158069066084.stdout:  Name: push.proposal - Function: salt.runner - Result: Changed Started: - 08:13:23.332504 Duration: 300.884 ms
2018-10-10T08:13:28.336 INFO:teuthology.orchestra.run.target158069066084.stdout:  Name: refresh_pillar1 - Function: salt.state - Result: Changed Started: - 08:13:23.633670 Duration: 410.107 ms
2018-10-10T08:13:28.336 INFO:teuthology.orchestra.run.target158069066084.stdout:  Name: verify pillar data - Function: salt.state - Result: Changed Started: - 08:13:24.044217 Duration: 2591.265 ms
2018-10-10T08:13:28.336 INFO:teuthology.orchestra.run.target158069066084.stdout:  Name: restore default proposal - Function: salt.state - Result: Changed Started: - 08:13:26.635947 Duration: 490.09 ms
2018-10-10T08:13:28.336 INFO:teuthology.orchestra.run.target158069066084.stdout:  Name: push.proposal - Function: salt.runner - Result: Changed Started: - 08:13:27.126645 Duration: 312.748 ms
2018-10-10T08:13:28.336 INFO:teuthology.orchestra.run.target158069066084.stdout:  Name: refresh_pillar2 - Function: salt.state - Result: Changed Started: - 08:13:27.439677 Duration: 397.701 ms
2018-10-10T08:13:28.336 INFO:teuthology.orchestra.run.target158069066084.stdout:
2018-10-10T08:13:28.337 INFO:teuthology.orchestra.run.target158069066084.stdout:Summary for target158069066084.teuthology_master
2018-10-10T08:13:28.337 INFO:teuthology.orchestra.run.target158069066084.stdout:--------------
2018-10-10T08:13:28.337 INFO:teuthology.orchestra.run.target158069066084.stdout:Succeeded: 114 (changed=104)
2018-10-10T08:13:28.337 INFO:teuthology.orchestra.run.target158069066084.stdout:Failed:      1
2018-10-10T08:13:28.337 INFO:teuthology.orchestra.run.target158069066084.stdout:--------------
2018-10-10T08:13:28.337 INFO:teuthology.orchestra.run.target158069066084.stdout:Total states run:     115
2018-10-10T08:13:28.337 INFO:teuthology.orchestra.run.target158069066084.stdout:Total run time:   495.548 s

```

**Comment by tserong** [comment]
This means the default storage profiles did not include /dev/vdc or /dev/vdd, but that the engulf detected those disks being used as OSDs somehow.

**Comment by tserong** [comment]
Let's give it a try ;-)

@susbot run teuthology

**Comment by tserong** [comment]
@susebot run teuthology

**Comment by tserong** [comment]
Now apparently there's a problem running `openstack server add volume target158069064229 target158069064229-3` :-/

**Comment by jschmid1** [comment]
> Now apparently there's a problem running `openstack server add volume target158069064229 target158069064229-3` :-/

dang, let's try it again.

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
> @jschmid1 would you be happy if I "fixed" this by moving the engulf functest before the remove functest?

Yeah, conceptionally it's the same.

**Comment by jschmid1** [comment]
> Note that we didn't hit this against master, because master doesn't include the remove functest in srv/salt/ceph/functests/1node/init.sls (nor does it include tuned, grafana or prometheus, but those omissions aren't related to this failure)

Those definitely should be added. I'll take care of this

**Comment by tserong** [comment]
Invalid update repo this time, I think.

**Comment by tserong** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by tserong** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by tserong** [comment]
Now it's an ssh problem? ("Permission denied (publickey)")

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology

**Pull request merged**
