### PR TITLE
monitoring: polulate alertmanager peers must run on salt master

### PR DESCRIPTION
**Pull request by jan--f**
Fixes: bsc#1137400

Signed-off-by: Jan Fajerski <jfajerski@suse.com>

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
may we have the #bsc in the commit message? @jan--f

**Comment by jan--f** [comment]
> may we have the #bsc in the commit message? @jan--f

it is...?

**Comment by jschmid1** [comment]
> > may we have the #bsc in the commit message? @jan--f
> 
> it is...?

my bad, I was just copypasting from the other pullrequest.

For an (easy) automated CHANGELOG generation, we'd have to put the bsc#xxxxx bit in the commit title.

I think that's not always possible though.. maybe the way forward is to have a script that parses commits for bsc# and generates a CHANGELOG based on that. Thoughts?

**Comment by jschmid1** [comment]
> Commit [ba4e625](https://github.com/SUSE/DeepSea/commit/ba4e625d8eed06019b02e6a60932a75641f45708) is _NOT OK_ for suite deepsea:tier2.
> Check tests results in the Jenkins job: http://ci.ses.suse.de:8080/job/pr-deepsea/230/

Seems like a worker/teuthology was going down right in the middle of the run. Re-running

**Comment by jschmid1** [comment]
@susebot run teuthology

**Pull request merged**
