### PR TITLE
[SES5] qa: run zypper refresh in try/wait loop

### PR DESCRIPTION
**Pull request by smithfarm**
backport of #980

### CODE REVIEW

**Comment by smithfarm** [comment]
please run health-ok suite

**Comment by smithfarm** [comment]
please run rgw suite

**Comment by kshtsk** [comment]
please run health-ok suite

**Comment by kshtsk** [comment]
please run rgw suite

**Comment by kshtsk** [comment]
please run health-ok suite

**Comment by kshtsk** [comment]
please run rgw suite

**Comment by smithfarm** [comment]
Tests passed

**Pull request merged**
