### PR TITLE
[SES5] iscsi: stop restart sequence when one iscsi gw fails to restart

### PR DESCRIPTION
**Pull request by rjfd**
Fixes: bsc#1143679

Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by jschmid1** [comment]
I messed up @rjfd , would you please rebase?

**Comment by rjfd** [comment]
@jschmid1 done

**Comment by jschmid1** [comment]
> @jschmid1 done

thanks!

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Pull request merged**
