### PR TITLE
[backport][SES5] Remove journal_size, if present

### PR DESCRIPTION
**Pull request by swiftgist**
backport of #1400 

Signed-off-by: Eric Jackson <ejackson@suse.com>

-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [ ] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@kshtsk teuthology died 

> 08:48:44 paramiko.ssh_exception.BadHostKeyException: (u'158.69.64.209', <paramiko.ecdsakey.ECDSAKey object at 0x7fde9bbb6250>, <paramiko.ecdsakey.ECDSAKey object at 0x7fde9bc1d610>)

**Comment by kshtsk** [comment]
@jschmid1 OVH is experiencing infrastructural issue now

**Comment by kshtsk** [comment]
@susebot run teuthology

**Pull request merged**
