### PR TITLE
[SES6] ganesha: report runner to give support info about nfs-ganesha

### PR DESCRIPTION
**Pull request by rjfd**
Signed-off-by: Ricardo Dias <rdias@suse.com>
(cherry picked from commit 45ee069b41a102e1e0935cdaaf4f0e9172957582)

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology deepsea/tier2/nfs-ganesha

**Comment by jschmid1** [comment]
sounds like unrelated failure

`16:23:21 java.lang.NullPointerExceptionBuild step 'MultiJob Phase' marked build as failure`

retriggering

**Comment by jschmid1** [comment]
@susebot run teuthology deepsea/tier2/nfs-ganesha

**Comment by jschmid1** [comment]
> sounds like unrelated failure
> 
> `16:23:21 java.lang.NullPointerExceptionBuild step 'MultiJob Phase' marked build as failure`
> 
> retriggering

same issue @kshtsk

**Comment by kshtsk** [comment]
@jschmid1 what do you mean unrelated failure?
rpm build phase is failed

**Comment by kshtsk** [comment]
@susebot run teuthology deepsea/tier2/nfs-ganesha

**Comment by kshtsk** [comment]
@jschmid1 I wonder which browser do you use that it inserts extra symbols '\r' to your message?

**Comment by kshtsk** [comment]
@susebot run teuthology deepsea/tier2/nfs-ganesha

**Comment by jschmid1** [comment]
> @jschmid1 I wonder which browser do you use that it inserts extra symbols '\r\n' to your message?
> 
> ```
> @susebot run teuthology deepsea/tier2/nfs-ganesha\r\n\r\n
> ```

chrome

**Comment by kshtsk** [comment]
@jschmid1 which version of chrome?

**Comment by jschmid1** [comment]
> @jschmid1 which version of chrome?

Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by kshtsk** [comment]
@susebot run teuthology deepsea/tier2/nfs-ganesha

**Comment by kshtsk** [comment]
copy pasting trigger phrase was not a good idea :-)

**Comment by kshtsk** [comment]
@susebot run teuthology deepsea/tier2/nfs-ganesha

**Comment by kshtsk** [comment]
@jschmid1 avoid using new lines in trigger messages, like you did, you are free to raise a defect in our jira though

**Pull request merged**
