### PR TITLE
cli: handles render failure when minion does not respond

### PR DESCRIPTION
**Pull request by rjfd**
Fixes: #1527

Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
> Commit [a6d140b](https://github.com/SUSE/DeepSea/commit/a6d140bf5968c87b095c5e764afcf37d256c649a) is _OK_ for suite suse:tier1.
> Check tests results in the Jenkins job: http://storage-ci.suse.de:8080/job/pr-deepsea/69/

@smithfarm CLI tests are disabled for master as it seems.

**Comment by rjfd** [comment]
@jschmid1 can we re-run the the tests on this PR now? I think the CLI tests are enabled again

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
@rjfd @jschmid1 The functests will fail due to #1580, but just from looking at the logs of the failed tests it should be obvious that this works, right?

**Pull request merged**
