### PR TITLE
ceph-volume: use re to extract json string from c-v output

### PR DESCRIPTION
**Pull request by jan--f**
This awful crutch should make life easier until
http://tracker.ceph.com/issues/38548 is fixed.

Signed-off-by: Jan Fajerski <jfajerski@suse.com>

### CODE REVIEW

**Comment by jan--f** [comment]
Not pretty but should at least get people working until c-v properly prints json.

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
ah, well.. it's not too bad :>

**Comment by jschmid1** [comment]
```
2019-04-30T08:31:36.941 INFO:teuthology.orchestra.run.target192168000087.stdout:[15/30] Executing runner disks.deploy...
2019-04-30T08:31:36.941 INFO:teuthology.orchestra.run.target192168000087.stdout:         |_  cmd.shell(ceph osd tree destroyed --format json)...
2019-04-30T08:31:37.383 INFO:teuthology.orchestra.run.target192168000087.stdout:               in target192168000087.teuthology... ok
2019-04-30T08:31:37.493 INFO:teuthology.orchestra.run.target192168000087.stdout:[15/30] Executing runner disks.deploy... fail
2019-04-30T08:31:37.501 INFO:teuthology.orchestra.run.target192168000087.stdout:Finished stage ceph.stage.3: succeeded=14/30 failed=1/30
2019-04-30T08:31:37.501 INFO:teuthology.orchestra.run.target192168000087.stdout:
2019-04-30T08:31:37.501 INFO:teuthology.orchestra.run.target192168000087.stdout:Failures summary:
2019-04-30T08:31:37.502 INFO:teuthology.orchestra.run.target192168000087.stdout:disks.deploy (/srv/modules/runners/disks.py):
2019-04-30T08:31:37.502 INFO:teuthology.orchestra.run.target192168000087.stdout:  Exception occurred in runner disks.deploy: Traceback (most recent call last):
2019-04-30T08:31:37.502 INFO:teuthology.orchestra.run.target192168000087.stdout:    File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 377, in low
2019-04-30T08:31:37.502 INFO:teuthology.orchestra.run.target192168000087.stdout:      data['return'] = func(*args, **kwargs)
2019-04-30T08:31:37.502 INFO:teuthology.orchestra.run.target192168000087.stdout:    File "/srv/modules/runners/disks.py", line 207, in deploy
2019-04-30T08:31:37.502 INFO:teuthology.orchestra.run.target192168000087.stdout:      return DriveGroups(**kwargs).call_out('deploy')
2019-04-30T08:31:37.503 INFO:teuthology.orchestra.run.target192168000087.stdout:    File "/srv/modules/runners/disks.py", line 150, in call_out
2019-04-30T08:31:37.503 INFO:teuthology.orchestra.run.target192168000087.stdout:      alias=alias))
2019-04-30T08:31:37.503 INFO:teuthology.orchestra.run.target192168000087.stdout:    File "/srv/modules/runners/disks.py", line 175, in call
2019-04-30T08:31:37.503 INFO:teuthology.orchestra.run.target192168000087.stdout:      'destroyed_osds': destroyed()
2019-04-30T08:31:37.503 INFO:teuthology.orchestra.run.target192168000087.stdout:    File "/srv/modules/runners/disks.py", line 228, in destroyed
2019-04-30T08:31:37.503 INFO:teuthology.orchestra.run.target192168000087.stdout:      tree = _parse_dirty_json(list(ret.values())[0]).get('nodes')
2019-04-30T08:31:37.504 INFO:teuthology.orchestra.run.target192168000087.stdout:    File "/srv/modules/runners/disks.py", line 192, in _parse_dirty_json
2019-04-30T08:31:37.504 INFO:teuthology.orchestra.run.target192168000087.stdout:      raise ValueError('No valid json found')
2019-04-30T08:31:37.504 INFO:teuthology.orchestra.run.target192168000087.stdout:  ValueError: No valid json found
```

**Comment by jan--f** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
one issue looks unrelated..(ganesha) 
the other _may_ indicate an issue.. re-running to be sure

**Comment by jschmid1** [comment]
https://github.com/SUSE/DeepSea/pull/1630#issuecomment-487931365 was meant for #1631 

```
2019-04-30T11:55:45.180 INFO:teuthology.orchestra.run.target192168000086.stdout:disks.deploy (/srv/modules/runners/disks.py):
2019-04-30T11:55:45.181 INFO:teuthology.orchestra.run.target192168000086.stdout:  Exception occurred in runner disks.deploy: Traceback (most recent call last):
2019-04-30T11:55:45.181 INFO:teuthology.orchestra.run.target192168000086.stdout:    File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 377, in low
2019-04-30T11:55:45.181 INFO:teuthology.orchestra.run.target192168000086.stdout:      data['return'] = func(*args, **kwargs)
2019-04-30T11:55:45.181 INFO:teuthology.orchestra.run.target192168000086.stdout:    File "/srv/modules/runners/disks.py", line 207, in deploy
2019-04-30T11:55:45.181 INFO:teuthology.orchestra.run.target192168000086.stdout:      return DriveGroups(**kwargs).call_out('deploy')
2019-04-30T11:55:45.181 INFO:teuthology.orchestra.run.target192168000086.stdout:    File "/srv/modules/runners/disks.py", line 150, in call_out
2019-04-30T11:55:45.181 INFO:teuthology.orchestra.run.target192168000086.stdout:      alias=alias))
2019-04-30T11:55:45.182 INFO:teuthology.orchestra.run.target192168000086.stdout:    File "/srv/modules/runners/disks.py", line 175, in call
2019-04-30T11:55:45.182 INFO:teuthology.orchestra.run.target192168000086.stdout:      'destroyed_osds': destroyed()
2019-04-30T11:55:45.182 INFO:teuthology.orchestra.run.target192168000086.stdout:    File "/srv/modules/runners/disks.py", line 228, in destroyed
2019-04-30T11:55:45.182 INFO:teuthology.orchestra.run.target192168000086.stdout:      tree = _parse_dirty_json(list(ret.values())[0]).get('nodes')
2019-04-30T11:55:45.182 INFO:teuthology.orchestra.run.target192168000086.stdout:    File "/srv/modules/runners/disks.py", line 192, in _parse_dirty_json
2019-04-30T11:55:45.182 INFO:teuthology.orchestra.run.target192168000086.stdout:      raise ValueError('No valid json found in {}'.format(maybe_json))
2019-04-30T11:55:45.183 INFO:teuthology.orchestra.run.target192168000086.stdout:  ValueError: No valid json found in
2019-04-30T11:55:45.183 INFO:teuthology.orchestra.run.target192168000086.stdout:  {"nodes":[],"stray":[]}
```

**Comment by jan--f** [comment]
@jschmid1 thanks...not sure why I couldn't find that. In any case that instance of `parse_dirty_json` was removed since it doesn't actually come from c-v.

**Comment by jan--f** [comment]
@susebot run teuthology

**Pull request merged**
