### PR TITLE
[SES6] Simplify management of tuned

### PR DESCRIPTION
**Pull request by swiftgist**
Disassociate the specific role names from their purpose.  Considering
that multiple roles can be assigned to a minion, applying a ceph-osd
profile to a gateway or having identical profiles for each role is
unnecessary.

Signed-off-by: Eric Jackson <ejackson@suse.com>
bnc:1142416
-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [ ] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
this implementation causes a bug in stage.3

```
2019-10-17T14:04:57.814 INFO:teuthology.orchestra.run.target192168000081.stdout:Parsing orchestration ceph.stage.3 steps... fail
2019-10-17T14:04:57.815 INFO:teuthology.orchestra.run.target192168000081.stdout:
2019-10-17T14:04:57.815 INFO:teuthology.orchestra.run.target192168000081.stdout:An error occurred when rendering one of the following states:
2019-10-17T14:04:57.815 INFO:teuthology.orchestra.run.target192168000081.stdout:    - ceph.tuned.throughput (/srv/salt/ceph/tuned/throughput)
2019-10-17T14:04:57.816 INFO:teuthology.orchestra.run.target192168000081.stdout:
2019-10-17T14:04:57.816 INFO:teuthology.orchestra.run.target192168000081.stdout:Error description:
2019-10-17T14:04:57.816 INFO:teuthology.orchestra.run.target192168000081.stdout:  - not ( I@roles:mgr or I@roles:mon ) and I@cluster:ceph: No minions matched the target. No command was sent, no jid was assigned.
2019-10-17T14:04:57.816 INFO:teuthology.orchestra.run.target192168000081.stdout:
2019-10-17T14:04:57.816 INFO:teuthology.orchestra.run.target192168000081.stdout:
```

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
what's the status here @swiftgist

**Comment by swiftgist** [comment]
Georgios is setting up a teuthology VM.

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
Previous error was missing a Makefile line... this last one about bluestore seems unrelated

**Comment by mgfritch** [comment]
> Previous error was missing a Makefile line... this last one about bluestore seems unrelated

`teuthology.deepsea:tier2.deepsea:tier2/filestore-to-bluestore-migration` failures appear fixed by PR  #1786

**Comment by mgfritch** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
Rebased

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@swiftgist is this still connected to the tuned changes?

**Comment by swiftgist** [comment]
The `rebuild.node` is failing because `cephdisks.find_osd_by_id` is only checking *block* and not *data*.  Here's the check:

```
                    if str(osd_id_search) == str(osd_id) and _lv.tags.get(
                            'ceph.type') == 'block':
                        devs.append(dev)
```

I thought that was modified at some point, but I don't recall at the moment.  The `osd.remove` call fails when `cephdisks.find_by_osd_id` returns an empty list.

**Comment by jschmid1** [comment]
right, this was introduced with c89a914e3 which seems to be not backported to SES6.

**Comment by gekios** [comment]
So I opened https://github.com/SUSE/DeepSea/pull/1794 for backporting the commit to SES6 branch.

**Comment by jschmid1** [comment]
#1794 is merged, please rebase @swiftgist

**Comment by swiftgist** [comment]
rebased

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
Appears that ceph-iscsi failed..... I'm not seeing the connection to tuned

**Comment by jschmid1** [comment]
This should land in `master` first

**Pull request merged**
