### PR TITLE
Install the ceph-mgr-dashboard on mgr nodes

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <ejackson@suse.com>
bsc: 1127770
Fixes: #1550 
-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [x] Referenced issues or internal bugtracker
- [x] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jan--f** [comment]
Should we also have a rescind step for this?

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by tserong** [comment]
srv/salt/ceph/mgr/dashboard/ still needs to be added to the Makefile and specfile

**Comment by smithfarm** [comment]
@swiftgist Could you add `Fixes: https://github.com/SUSE/DeepSea/issues/1550` to the commit message and PR description?

**Comment by jschmid1** [comment]
> srv/salt/ceph/mgr/dashboard/ still needs to be added to the Makefile and specfile

The logs confirm this.

Specified SLS ceph.mgr.dashboard in saltenv base is not available on the salt master or through a configured fileserver

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
> srv/salt/ceph/mgr/dashboard/ still needs to be added to the Makefile and specfile

@swiftgist ^^^^^^^

**Comment by swiftgist** [comment]
@susebot run teuthology

**Pull request merged**
