### PR TITLE
Add Prometheus and Grafana roles (SES-199)

### PR DESCRIPTION
**Pull request by jan--f**
Adds two new roles and deployment, rescind and restart steps.

Supersedes #1533

### CODE REVIEW

**Comment by jan--f** [comment]
@jschmid1 good to go from my perspective. the make-rpm failure seems unrelated?

**Comment by jschmid1** [comment]
does it?

```
RPM build errors:
[91merror: Installed (but unpackaged) file(s) found:
   /srv/salt/ceph/rescind/grafana/default-nop.sls
   /srv/salt/ceph/rescind/grafana/default.sls
   /srv/salt/ceph/rescind/grafana/init.sls
   /srv/salt/ceph/rescind/prometheus/default-nop.sls
   /srv/salt/ceph/rescind/prometheus/default.sls
   /srv/salt/ceph/rescind/prometheus/init.sls
    File listed twice: /srv/salt/ceph/apparmor/files/ceph.d
    File listed twice: /srv/salt/ceph/apparmor/files/ceph.d/common
    File listed twice: /srv/salt/ceph/configuration/files/ceph.conf.checksum
    File listed twice: /usr/lib/python3.6/site-packages/deepsea-0.9.12+12.g08972ae8-py3.6.egg-info/PKG-INFO
    File listed twice: /usr/lib/python3.6/site-packages/deepsea-0.9.12+12.g08972ae8-py3.6.egg-info/SOURCES.txt
    File listed twice: /usr/lib/python3.6/site-packages/deepsea-0.9.12+12.g08972ae8-py3.6.egg-info/dependency_links.txt
    File listed twice: /usr/lib/python3.6/site-packages/deepsea-0.9.12+12.g08972ae8-py3.6.egg-info/entry_points.txt
    File listed twice: /usr/lib/python3.6/site-packages/deepsea-0.9.12+12.g08972ae8-py3.6.egg-info/top_level.txt
    Installed (but unpackaged) file(s) found:
   /srv/salt/ceph/rescind/grafana/default-nop.sls
   /srv/salt/ceph/rescind/grafana/default.sls
   /srv/salt/ceph/rescind/grafana/init.sls
   /srv/salt/ceph/rescind/prometheus/default-nop.sls
   /srv/salt/ceph/rescind/prometheus/default.sls
   /srv/salt/ceph/rescind/prometheus/init.sls
```

**Comment by jan--f** [comment]
@jschmid1 my bad, must've clicked the wrong link

**Comment by jan--f** [comment]
@jschmid1 how about it on a friday afternoon ;)

**Comment by jschmid1** [comment]
Things that come to my mind which are on the TODO list:

* adapt the deepsea-teuthology tasks (add dedicated monitoring roles, @smithfarm can probably help with this)
* This will probably need a followup PR to migrate from the 0.8.x way to the new one.
   * Dependent on #1545

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
```
2019-02-25T16:04:59.672 INFO:teuthology.orchestra.run.target192168000033.stderr:deepsea.stage_parser.StateRenderingException: ['I@roles:prometheus and I@cluster:ceph: No minions matched the target. No command was sent, no jid was assigned.\n']
```

**Comment by jschmid1** [comment]
It seems the roles were not assigned correctly

**Comment by jschmid1** [comment]
Giving this a shot in my env now

**Comment by jan--f** [comment]
I haven'T covered the case where no monitoring roles are assigned. I thought if no minions match a target it'll simply not do anything. I'll add a condition to avoid the `No minions matched the target. No command was sent, no jid was assigned.` error.

**Comment by jschmid1** [comment]
> I haven'T covered the case where no monitoring roles are assigned. I thought if no minions match a target it'll simply not do anything. I'll add a condition to avoid the `No minions matched the target. No command was sent, no jid was assigned.` error.

What's the expected behavior in no roles are assigned?

* Fallback to a subset of nodes?
* Bail out on stage-validation?

**Comment by jan--f** [comment]
> What's the expected behavior in no roles are assigned?
Do nothing

**Comment by jschmid1** [comment]
> Do nothing

Maybe a warning in a validation saying:

You don't have any prometheus/grafana roles assigend, hence no monitoring stack will be deployed?

**Comment by jan--f** [comment]
> Maybe a warning in a validation saying:
> 
> You don't have any prometheus/grafana roles assigend, hence no monitoring stack will be deployed?

Oh sure. Right now I'm more concerned with the failed states though.

**Comment by jan--f** [comment]
ok ready to merge as soon as @smithfarm give a green light.

**Comment by jschmid1** [comment]
Also tried deployment & teardown of grafana/prometheus on my cluster. Works like a charm @jan--f

**Comment by smithfarm** [comment]
oops, too late - I just merged https://github.com/SUSE/ceph/pull/261 and was going to tell susebot to run teuthology on this

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
> oops, too late - I just merged [SUSE/ceph#261](https://github.com/SUSE/ceph/pull/261) and was going to tell susebot to run teuthology on this

Was the run successful :>?

**Comment by smithfarm** [comment]
> Was the run successful :>?

The susebot ignores test requests on merged PRs, so no run got triggered.

**Pull request merged**
