### PR TITLE
doc: add contribution guidelines

### PR DESCRIPTION
**Pull request by theanalyst**
Signed-off-by: Abhishek Lekshmanan <abhishek@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
lgtm

**Comment by jschmid1** [comment]
looks good

**Comment by jan--f** [comment]
yep looks great!

**Comment by jan--f** [comment]
oh maybe add a link from the readme?

**Comment by LenzGr** [comment]
Looks good to me - thanks! Yes, it might make sense to refer to this file from the `README.md` as well.

**Comment by theanalyst** [comment]
@jan--f @LenzGr updated

**Comment by rjfd** [comment]
LGTM :+1:

**Comment by swiftgist** [comment]
Should the 'git commit' be 'git commit -s' to help with the signoff?

**Comment by theanalyst** [comment]
@swiftgist updated

**Pull request merged**
