### PR TITLE
[backport][SES5] qa: add openstack functional test to CI

### PR DESCRIPTION
**Pull request by smithfarm**
Backport for:

* https://github.com/SUSE/DeepSea/pull/1342
* https://github.com/SUSE/DeepSea/pull/1346
* https://github.com/SUSE/DeepSea/pull/1355

NOTE: to be tested and merged together with companion PR: https://github.com/SUSE/ceph/pull/205

**Checklist:**
- [x] Added unittests and or functional tests
~~- [ ] Adapted documentation~~
~~- [ ] Referenced issues or internal bugtracker~~
- [x] open SUSE/ceph.git companion PR
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by smithfarm** [comment]
SUSE/ceph.git companion PR: https://github.com/SUSE/ceph/pull/205

**Comment by jschmid1** [comment]
@smithfarm we have a mergeconflict here

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
@jschmid1 Note this needs a special branch of SUSE/ceph.git for testing. I'm going to schedule a run in my private teuthology instance.

**Comment by smithfarm** [comment]
Testing:

* `suse/tier1` http://149.202.174.223:8081/ubuntu-2018-09-06_19:54:19-suse:tier1-ses5---basic-openstack/ (PASS)
* `suse/tier2`

**Comment by smithfarm** [comment]
```
2018-09-06T20:27:34.535 INFO:teuthology.orchestra.run.target149202170005.stdout:  Name: make sure grafana state is applied - Function: salt.state - Result: Changed Started: - 20:26:55.209926 Duration: 3344.478 ms
2018-09-06T20:27:34.535 INFO:teuthology.orchestra.run.target149202170005.stdout:  Name: make sure grafana is running - Function: salt.state - Result: Clean Started: - 20:26:58.554702 Duration: 1025.708 ms
2018-09-06T20:27:34.535 INFO:teuthology.orchestra.run.target149202170005.stdout:  Name: make sure prometheus state is applied - Function: salt.state - Result: Clean Started: - 20:26:59.580921 Duration: 1643.027 ms
2018-09-06T20:27:34.535 INFO:teuthology.orchestra.run.target149202170005.stdout:  Name: make sure prometheus is running - Function: salt.state - Result: Clean Started: - 20:27:01.224521 Duration: 1163.499 ms
2018-09-06T20:27:34.536 INFO:teuthology.orchestra.run.target149202170005.stdout:  Name: apply ceph.openstack - Function: salt.state - Result: Changed Started: - 20:27:02.388415 Duration: 6480.276 ms
2018-09-06T20:27:34.537 INFO:teuthology.orchestra.run.target149202170005.stderr:[DEBUG   ] LazyLoaded local_cache.prep_jid
2018-09-06T20:27:34.537 INFO:teuthology.orchestra.run.target149202170005.stderr:[INFO    ] Runner completed: 20180906201902345441
2018-09-06T20:27:34.538 INFO:teuthology.orchestra.run.target149202170005.stderr:[DEBUG   ] Runner return: {'outputter': 'highstate', 'retcode': 0}
2018-09-06T20:27:34.538 INFO:teuthology.orchestra.run.target149202170005.stdout:  Name: verify users - Function: salt.state - Result: Changed Started: - 20:27:08.868993 Duration: 1452.258 ms
2018-09-06T20:27:34.538 INFO:teuthology.orchestra.run.target149202170005.stdout:  Name: verify pools - Function: salt.state - Result: Changed Started: - 20:27:10.321588 Duration: 623.472 ms
2018-09-06T20:27:34.538 INFO:teuthology.orchestra.run.target149202170005.stdout:  Name: clean environment at end - Function: salt.state - Result: Changed Started: - 20:27:10.945744 Duration: 7297.932 ms
2018-09-06T20:27:34.538 INFO:teuthology.orchestra.run.target149202170005.stdout:  Name: apply ceph.openstack (prefix=smoketest) - Function: salt.state - Result: Changed Started: - 20:27:18.244021 Duration: 6445.657 ms
2018-09-06T20:27:34.539 INFO:teuthology.orchestra.run.target149202170005.stdout:  Name: verify users (prefix=smoketest) - Function: salt.state - Result: Changed Started: - 20:27:24.690137 Duration: 1261.998 ms
2018-09-06T20:27:34.539 INFO:teuthology.orchestra.run.target149202170005.stdout:  Name: verify pools (prefix=smoketest) - Function: salt.state - Result: Changed Started: - 20:27:25.952452 Duration: 618.846 ms
2018-09-06T20:27:34.539 INFO:teuthology.orchestra.run.target149202170005.stdout:  Name: clean environment at end (prefix=smoketest) - Function: salt.state - Result: Changed Started: - 20:27:26.571784 Duration: 7510.501 ms
2018-09-06T20:27:34.539 INFO:teuthology.orchestra.run.target149202170005.stdout:
2018-09-06T20:27:34.540 INFO:teuthology.orchestra.run.target149202170005.stdout:Summary for target149202170005.teuthology_master
2018-09-06T20:27:34.540 INFO:teuthology.orchestra.run.target149202170005.stdout:--------------
2018-09-06T20:27:34.540 INFO:teuthology.orchestra.run.target149202170005.stdout:Succeeded: 105 (changed=95)
2018-09-06T20:27:34.540 INFO:teuthology.orchestra.run.target149202170005.stdout:Failed:      0
2018-09-06T20:27:34.540 INFO:teuthology.orchestra.run.target149202170005.stdout:--------------
2018-09-06T20:27:34.541 INFO:teuthology.orchestra.run.target149202170005.stdout:Total states run:     105
2018-09-06T20:27:34.541 INFO:teuthology.orchestra.run.target149202170005.stdout:Total run time:   500.948 s
```

**Comment by smithfarm** [comment]
@jschmid1 IMO this PR passed integration testing. One of the four failures is due to a version mismatch which will go away soon, and the other three are #1364 and #1365 (for both of which I don't see how they could be related to this PR).

**Pull request merged**
