### PR TITLE
[SES5] monitoring: update smartmon.sh, fix label dimension inconsistency

### PR DESCRIPTION
**Pull request by jan--f**
Signed-off-by: Jan Fajerski <jfajerski@suse.com>

### CODE REVIEW

**Comment by jan--f** [comment]
Seems there's a potential issue, waiting on feedback.

**Comment by jschmid1** [comment]
Any reference to that change?

**Comment by jschmid1** [comment]
retest this please

**Comment by tserong** [comment]
It's difficult for me to tell how much of this is reformatting and how much is fixing something (I don't think I actually looked at this script before :-/)

**Comment by jan--f** [comment]
The issue is that the old script potentially causes this log message: `has label dimensions inconsistent with previously collected metrics in the same metric family`. The initial fix didn't deal well with nvme drives (now fixed).
Still waiting on feedback, but I believe this should fix the issue.

Code-wise this is the script from the node_exporter repo plus the fix for nvme drives. Will upstream the nvme fix.

**Comment by jan--f** [comment]
retest this please

**Comment by jan--f** [comment]
Got confirmation from a customer that this fixes their issue. I pushed the fix upstream as well https://github.com/prometheus/node_exporter/pull/1313

**Comment by jan--f** [comment]
> One question: where'd the `clean_up` stuff come from (lines 12-25)? I can't seem to see that in the version in the node_exporter repo, although it certainly seems sensible to have that piece IMO. Maybe that should be added upstream too?

Yeah I added locking via a mkdir and the relevant cleanup. Not really sure if thats necessary, but assume a long running invocation or multiple invocations this should avoid the output file to become corrupted. Will try to upstream it.

**Pull request merged**
