### PR TITLE
[SES5] Remove igw_config setting during purge

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <ejackson@suse.com>
bnc#1112247

-----------------

**Checklist:**
- [x] Added unittests and or functional tests
- [ ] Adapted documentation
- [x] Referenced issues or internal bugtracker
- [x] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
ignore this failure, we had to restart one of our workers

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Pull request merged**
