### PR TITLE
modules: expr_form has been deprecated over tgt_type

### PR DESCRIPTION
**Pull request by jan--f**

### CODE REVIEW

**Comment by jschmid1** [comment]
adapt tests accordingly please

**Comment by jan--f** [comment]
@jschmid1 done

**Comment by jschmid1** [comment]
retest this please

**Comment by jschmid1** [comment]
@jan--f 

```
AssertionError: expected call not found. Expected: cmd('target*', 'dg.test_command', expr_form='compound', kwarg={'filter_args': {'args'}, 'dry_run': False, 'include_unavailable': True, 'destroyed_osds': {'data1': [1, 2, 3]}}) Actual: cmd('target*', 'dg.test_command', kwarg={'filter_args': {'args'}, 'dry_run': False, 'include_unavailable': True, 'destroyed_osds': {'data1': [1, 2, 3]}}, tgt_type='compound')
```

**Comment by jan--f** [comment]
retest this please

**Pull request merged**
