### PR TITLE
[DNM] Temporary PR for testing changes to qa/tasks/deepsea.py

### PR DESCRIPTION
**Pull request by smithfarm**

### CODE REVIEW

**Comment by smithfarm** [comment]
@susebot run teuthology deepsea/tier3/mgr-plugins using wip-qa-drop-dashboard-deployment

**Comment by smithfarm** [comment]
@susebot run teuthology deepsea/tier1

**Comment by smithfarm** [comment]
@susebot run teuthology deepsea/tier4/nfs-ganesha using wip-qa-nfs-ganesha

**Comment by smithfarm** [comment]
@susebot run teuthology deepsea/tier4/nfs-ganesha using wip-qa-nfs-ganesha

**Comment by smithfarm** [comment]
@susebot run teuthology deepsea/tier4/nfs-ganesha using wip-qa-nfs-ganesha

**Comment by smithfarm** [comment]
@rjfd OK, I finally have a proper test run of your ganesha_smoke_test.sh script. The cephfs variant works fine, but rgw fails like this:

```
2019-04-09T18:56:24.592 INFO:teuthology.orchestra.run.target192168000033.stderr:+ showmount -e target192168000042
2019-04-09T18:56:24.612 INFO:teuthology.orchestra.run.target192168000033.stdout:Export list for target192168000042:
2019-04-09T18:56:24.612 INFO:teuthology.orchestra.run.target192168000033.stdout:Mount RGW export path=bucket1
2019-04-09T18:56:24.613 INFO:teuthology.orchestra.run.target192168000033.stderr:+ echo 'Mount RGW export path=bucket1'
2019-04-09T18:56:24.613 INFO:teuthology.orchestra.run.target192168000033.stderr:+ mount_export target192168000042 / /root/mnt
2019-04-09T18:56:24.613 INFO:teuthology.orchestra.run.target192168000033.stderr:+ local daemon=target192168000042
2019-04-09T18:56:24.613 INFO:teuthology.orchestra.run.target192168000033.stderr:+ local ex_path=/
2019-04-09T18:56:24.613 INFO:teuthology.orchestra.run.target192168000033.stderr:+ local fs_path=/root/mnt
2019-04-09T18:56:24.614 INFO:teuthology.orchestra.run.target192168000033.stderr:+ test '!' -e /root/mnt
2019-04-09T18:56:24.614 INFO:teuthology.orchestra.run.target192168000033.stderr:+ mkdir -p /root/mnt
2019-04-09T18:56:24.617 INFO:teuthology.orchestra.run.target192168000033.stderr:+ test -d /root/mnt
2019-04-09T18:56:24.617 INFO:teuthology.orchestra.run.target192168000033.stderr:+ mount -t nfs target192168000042:/ /root/mnt
2019-04-09T18:56:24.935 INFO:teuthology.orchestra.run.target192168000033.stdout:Writing into RGW export
2019-04-09T18:56:24.936 INFO:teuthology.orchestra.run.target192168000033.stderr:+ echo 'Writing into RGW export'
2019-04-09T18:56:24.936 INFO:teuthology.orchestra.run.target192168000033.stderr:+ echo 'Hello World!'
2019-04-09T18:56:24.937 INFO:teuthology.orchestra.run.target192168000033.stderr:scripts/ganesha_smoke_test.sh: line 208: /root/mnt/rgw/bucket1/hello.txt: No such file or directory
2019-04-09T18:56:24.940 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
  File "/home/ubuntu/teuthology/teuthology/run_tasks.py", line 95, in run_tasks
    run_one_task(taskname, stack, timer, ctx=ctx, config=config)
  File "/home/ubuntu/teuthology/teuthology/run_tasks.py", line 74, in run_one_task
    manager.__enter__()
  File "/home/ubuntu/teuthology/teuthology/task/__init__.py", line 121, in __enter__
    self.begin()
  File "/home/ubuntu/src/github.com_SUSE_ceph_wip-qa-nfs-ganesha/qa/tasks/deepsea.py", line 1788, in begin
    method(**kwargs)
  File "/home/ubuntu/src/github.com_SUSE_ceph_wip-qa-nfs-ganesha/qa/tasks/deepsea.py", line 1695, in ganesha_smoke_test
    args=args,
  File "/home/ubuntu/src/github.com_SUSE_ceph_wip-qa-nfs-ganesha/qa/tasks/scripts.py", line 40, in run
    remote.run(label=script_name, args=cmd)
  File "/home/ubuntu/teuthology/teuthology/orchestra/remote.py", line 205, in run
    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
  File "/home/ubuntu/teuthology/teuthology/orchestra/run.py", line 403, in run
    r.wait()
  File "/home/ubuntu/teuthology/teuthology/orchestra/run.py", line 166, in wait
    label=self.label)
CommandFailedError: Command failed (ganesha_smoke_test.sh) on target192168000033 with status 1: 'sudo bash scripts/ganesha_smoke_test.sh --rgw'
```

Full teuthology.log: http://storage-ci.suse.de:8080/job/pr-deepsea/151/testReport/teuthology/deepsea_tier4_nfs-ganesha/_0_salt_yaml_1_deepsea_yaml_2_services_and_test_rgw_yaml_boilerplate__ceph_cm_salt_yaml_disable_tuned_yaml_zypper_dup_yaml__distros_sle_15_1_yaml_openstack_yaml_/attachments/teuthology-12729.log

**Comment by rjfd** [comment]
@smithfarm the cause of the problem comes from this:
```
2019-04-09T18:56:21.574 INFO:teuthology.orchestra.run.target192168000033.stderr:+++ result='{"detail": "Cannot create this export. FSAL '\''RGW'\'' cannot be managed by the dashboard.", "component": "nfs", "status": 400, "task": {"name": "nfs/create", "metadata": {"path": "bucket1", "fsal": "RGW", "cluster_id": "_default_"}}}'
```

Apparently DeepSea failed to correctly configure RGW in the dashboard.

**Comment by rjfd** [comment]
I also found this:
```
2019-04-09T18:51:45.163 DEBUG:tasks.deepsea.orch:munged config is {'stage': 4}
2019-04-09T18:51:45.164 INFO:teuthology.orchestra.run.target192168000042:Running: 'sudo salt-run jobs.active 2>/dev/null'
2019-04-09T18:51:54.395 INFO:tasks.deepsea.orch:NFS-Ganesha set No_root_squash
2019-04-09T18:51:54.396 INFO:teuthology.orchestra.run.target192168000042:Running: "sudo sed -i '/Access_Type = RW;/a \tSquash = No_root_squash;' /srv/salt/ceph/ganesha/files/ganesha.conf.j2"
```

The above "sed" can be dropped has ganesha exports are no longer stored in `ganesha.conf.j2` file

**Comment by smithfarm** [comment]
Thanks to @ricardoasmarques I was able to open http://tracker.ceph.com/issues/39252 and I now have a workaround that should get the rgw test case to pass.

**Comment by smithfarm** [comment]
@susebot run teuthology deepsea/tier4/nfs-ganesha using wip-qa-nfs-ganesha

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
@susebot run teuthology using wip-qa-nfs-ganesha

**Pull request closed without merging**
