### PR TITLE
Use FQDN hostname also for MASTER_MINION

### PR DESCRIPTION
**Pull request by dzedro**
Fixes #
https://openqa.suse.de/tests/2139403#step/deepsea_testsuite/29

### CODE REVIEW

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
This should be OK - just checking whether it breaks the CI.

**Comment by dzedro** [comment]
I'm not sure if master must have fqdn hostname, but I did see use of `hostname --fqdn` in other code just in echo, otherwise `salt $MASTER_MINION* test.ping` would work without --fqdn

**Comment by jschmid1** [comment]
@smithfarm This needs a forwardport to SUSE/ceph.git, right? qa/ is no longer present in Deepsea:master

**Comment by smithfarm** [comment]
@jschmid1 Correct. I'll take care of it.

**Comment by jschmid1** [comment]
[Bug 1110852 - /srv/salt/ceph/restart/mds/default-shrink.sls is using the mds ids as returned by ceph as minion names without adding a "*" suffix](https://trello.com/c/CoWDloFH/96-bug-1110852-srv-salt-ceph-restart-mds-default-shrinksls-is-using-the-mds-ids-as-returned-by-ceph-as-minion-names-without-adding)

**Comment by smithfarm** [comment]
forward-port is done

**Pull request merged**
