### PR TITLE
qa: drop health-ok.sh and associated scripting

### PR DESCRIPTION
**Pull request by smithfarm**
All of this has been moved to SUSE/ceph.git ses6 branch. The
new location is

https://github.com/SUSE/ceph/tree/ses6/qa/workunits/deepsea    

- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
retest this please

**Comment by smithfarm** [comment]
```
Processing files: deepsea-0.9.6+187.g7e689e0b-0.noarch
error: Directory not found: /home/jenkins/rpmbuild/BUILDROOT/deepsea-0.9.6+187.g7e689e0b-0.x86_64/usr/lib/deepsea
    Directory not found: /home/jenkins/rpmbuild/BUILDROOT/deepsea-0.9.6+187.g7e689e0b-0.x86_64/usr/lib/deepsea
```

**Comment by smithfarm** [comment]
@jschmid1 I am preserving the `deepsea-qa` RPM for now, since it contains all the functional test orchestrations, but this also implies that these orchestrations are not availble to users on SLES, because the deepsea-qa rpm lives on the internal media.

If we wanted SLES users to be able to run the functest orchestrations, we would need to either move them into the main deepsea RPM or start shipping the deepsea-qa RPM.

Your thoughts?

**Comment by jschmid1** [comment]
Erhm, I don't think we should enable people to run the functional tests on their own. This will probably create more confusion and insecurity/distrust when something fails due to certain prerequisites..

I'd vote for keeping the -qa separate on the internal media and not ship it.

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
@susebot run teuthology deepsea/tier2/health-ok

**Comment by smithfarm** [comment]
@susebot run teuthology deepsea/tier2/health-ok

**Comment by smithfarm** [comment]
@jschmid1 I think https://github.com/SUSE/DeepSea/pull/1394#issuecomment-424338367 is enough testing. This could be merged.

**Pull request merged**
