### PR TITLE
Some fixes for new monitoring deployment

### PR DESCRIPTION
**Pull request by jan--f**
Forgot a few things.

Fixes bsc#1134467

### CODE REVIEW

**Comment by jschmid1** [comment]
retest this please

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
from the logs:

```
2019-05-10T11:33:38.932 INFO:teuthology.orchestra.run.target192168000113.stdout:[2/39] Executing state ceph.monitoring.prometheus...
2019-05-10T11:34:01.716 INFO:teuthology.orchestra.run.target192168000113.stdout:         |_  target192168000113.teuthology: golang-github-prometheus-prometheus ok
2019-05-10T11:34:14.741 INFO:teuthology.orchestra.run.target192168000113.stdout:         |_  target192168000113.teuthology: ceph-prometheus-alerts fail
2019-05-10T11:34:14.904 INFO:teuthology.orchestra.run.target192168000113.stdout:         |_  target192168000113.teuthology: /etc/prometheus/prometheus.yml ok
2019-05-10T11:34:15.413 INFO:teuthology.orchestra.run.target192168000113.stdout:         target192168000113.teuthology... fail
```

**Comment by jan--f** [comment]
The error depends on https://github.com/ceph/ceph/pull/27996

**Pull request merged**
