### PR TITLE
[backport][ses5] cli: filter out test.nop steps and don't report [init] step errors

### PR DESCRIPTION
**Pull request by smithfarm**
Backport of https://github.com/SUSE/DeepSea/pull/1246

### CODE REVIEW

**Comment by smithfarm** [comment]
I guess this is relevant for SES5 after all. . .

**Comment by smithfarm** [comment]
The new tests introduced by this PR are failing with

```
E   SaltClientError: Could not access /var/cache/salt. Please give jenkins read permissions.
```

I'm guessing some other commit needs to be cherry-picked, but which one?

**Comment by smithfarm** [comment]
@jschmid1 It looks like they *are* excluded in master PR test runs, but by what mechanism? In other words, what is missing to exclude them for SES5 PR test runs as well?

**Comment by jschmid1** [comment]
I think it should be that https://github.com/SUSE/DeepSea/blob/master/tox.ini#L17-L17

**Comment by smithfarm** [comment]
@jschmid1 Passing Jenkins now: please have another look?

**Comment by smithfarm** [comment]
@alexandergraul It seems like you're saying we could just drop the py-coverage/codecov commits and fix the unit tests by simply adding `--ignore cli/` to the relevant line in tox.ini. Correct?

If you guys think that's a better way to go, I'll be happy to do it.

**Comment by alexandergraul** [comment]
@smithfarm yes, the only relevant part of e931102 and 1d52c88 is ` --ignore cli/` unless I am missing something.
I think it would be better to just add that without those two commits to keep the intention clear and only change what is actually needed.

**Pull request merged**
