### PR TITLE
Remove migration orchestrations

### PR DESCRIPTION
**Pull request by swiftgist**
The `osd.redeploy` function does not exist.  Neither orchestration has
been working for some time.

Signed-off-by: Eric Jackson <ejackson@suse.com>
-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [ ] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
`deepsea/tier2/filestore-to-bluestore-migration` uses `rebuild.node` and `deepsea/tier2/drive-replacement` uses `osd.replace` so I guess this is OK?

**Comment by shyukri** [comment]
> `deepsea/tier2/filestore-to-bluestore-migration` uses `rebuild.node` and `deepsea/tier2/drive-replacement` uses `osd.replace` so I guess this is OK?

True. There is no test code calling `osd.redeploy`

**Pull request merged**
