### PR TITLE
nfs-ganesha: deploy ganesha configuration in RADOS pool

### PR DESCRIPTION
**Pull request by rjfd**
This PR changes the deployment of nfs-ganesha to match the requirements of ceph-dashboard.

Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
from the logs: 

> deepsea.stage_parser.StageRenderingException: ["Rendering SLS 'base:ceph.stage.ganesha.core.default' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'master.find_pool'"]

**Comment by rjfd** [comment]
@jschmid1 ah, yes, that module function is implemented in PR #1573

**Comment by jschmid1** [comment]
#1573 is merged, if you rebase we can trigger a new test run

**Comment by rjfd** [comment]
@susebot run teuthology

**Comment by rjfd** [comment]
@jschmid1 rebased and triggered a test run

**Comment by smithfarm** [comment]
nfs-ganesha test case is broken in master now

**Pull request merged**
