### PR TITLE
[SES5] ceph.time: work around buggy "service.running"

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: https://github.com/SUSE/DeepSea/issues/1822
Signed-off-by: Nathan Cutler <ncutler@suse.com>

-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [x] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by smithfarm** [comment]
This can be tested by running the following command with and without the patches in https://github.com/SUSE/sesdev/pull/108

```
sesdev create ses5 ses5_test
```

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
The test failures are unrelated to the PR, and actually I don't think teuthology exercises this code at all...

The test failures are caused by bad repos:

```
2020-02-18T07:48:35.400 INFO:teuthology.orchestra.run.target192168000069.stdout:Package 'salt' is not available in your repositories. Cannot reinstall, upgrade, or downgrade.
2020-02-18T07:48:35.400 INFO:teuthology.orchestra.run.target192168000069.stdout:Package 'salt-api' is not available in your repositories. Cannot reinstall, upgrade, or downgrade.
2020-02-18T07:48:35.400 INFO:teuthology.orchestra.run.target192168000069.stdout:Package 'salt-master' is not available in your repositories. Cannot reinstall, upgrade, or downgrade.
2020-02-18T07:48:35.400 INFO:teuthology.orchestra.run.target192168000069.stdout:Package 'salt-minion' is not available in your repositories. Cannot reinstall, upgrade, or downgrade.
```

**Comment by jschmid1** [comment]
> The test failures are unrelated to the PR, and actually I don't think teuthology exercises this code at all...

It should exercise it during the initial deployment, huh?

Anyways, you seem to have tested that locally with success.. merging..

**Comment by smithfarm** [comment]
> It should exercise it during the initial deployment, huh?

I don't think so - if it did, Stage 3 would surely fail.

In teuthology, each node has a running NTPD syncing to external time servers and `time_init` is not set in the pillar.

**Pull request merged**
