### PR TITLE
remove/replace: add path to status report for better identification

### PR DESCRIPTION
**Pull request by jschmid1**
Signed-off-by: Joshua Schmid <jschmid@suse.de>

before:

`salt-run osd.remove(replace) $osd_id`
[..snip..]     
```                                                                                                                                                                                                                                                                                                                                              
14:                                                                                                                                                                                                                                            
    True 
```

after:

```
14:                                                                                                                                                                                      
    ----------                                                                                                                                                                                                                                 
    path:                                                                                                                                                                                                                                      
        /dev/vdb                                                                                                                                                                                                                               
    returncode:                                                                                                                                                                                                                                
        True               
```

suse_internal: bnc#1142663

-----------------

**Checklist:**
~- [ ] Added unittests and or functional tests~
~- [ ] Adapted documentation~
~- [ ] Referenced issues or internal bugtracker~
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
Is this for bnc#1142663?  It's the request for the model and serial number.

**Comment by jschmid1** [comment]
> Is this for bnc#1142663? It's the request for the model and serial number.

You're right. I wasn't aware that there is a bug for this. Adding to the PR body.

**Comment by tserong** [comment]
Shouldn't this then print the model and serial number in addition to the device path?

**Comment by jschmid1** [comment]
> Shouldn't this then print the model and serial number in addition to the device path?

while the user could technically retrieve this by searching for the device path, this would probably save some time :+1: 

In a perfect world we should even hook a `disk.led` call to a `replace/remove` call. Would that be useful right now?

**Comment by tserong** [comment]
> In a perfect world we should even hook a `disk.led` call to a `replace/remove` call. Would that be useful right now?

Maybe? Although I'm kinda inclined to leave that until someone explicitly asks for it to happen automatically :-)

**Comment by jschmid1** [comment]
> > In a perfect world we should even hook a `disk.led` call to a `replace/remove` call. Would that be useful right now?
> 
> Maybe? Although I'm kinda inclined to leave that until someone explicitly asks for it to happen automatically :-)

adapted the return to: 

* path
* returncode
* model


`serial` is postponed until present in `ceph-volume inventory` json output, as discussed.

**Comment by jschmid1** [comment]
Added a fix dc5e1ef for a bug that was introduced with #1690

**Pull request merged**
