### PR TITLE
qa: test script fixes needed to revive pynfs.sh

### PR DESCRIPTION
**Pull request by smithfarm**
The scripts were not recognizing "--help", for example. Also added "--cli"
option to pynfs.sh.

Backport: https://github.com/SUSE/DeepSea/pull/899

### CODE REVIEW

**Comment by smithfarm** [comment]
@jschmid1 Please whitelist me?

**Comment by jschmid1** [comment]
> @jschmid1 Please whitelist me?

@smithfarm I did in the past. Seems jenkins can't read the global configuration of that plugin. Added you as a 'Admin' for each of the jobs.

**Comment by jschmid1** [comment]
please run ganesha suite

**Comment by smithfarm** [comment]
@jschmid1 Thanks. Please note that pynfs.sh is not run by the ganesha suite (atm, afaik) because some of the PyNFS tests are failing. See https://bugzilla.suse.com/show_bug.cgi?id=1076596

**Comment by smithfarm** [comment]
I can't review my own PR, but I'm satisfied with it now 👍 

pynfs test runs to completion: http://147.135.134.5/ubuntu-2018-01-18_15:37:44-deepsea:ceph-test:pynfs-ses5---basic-openstack/10/teuthology.log

**Comment by jschmid1** [comment]
ok, let's merge it then.

**Pull request merged**
