### PR TITLE
qa: health-ok.sh: enable testing of OSD configurations

### PR DESCRIPTION
**Pull request by smithfarm**
This PR refactors the health-ok.sh script to allow OSD configuration to be chosen at runtime from among those in `qa/osd-configs/ovh` (this directory is hard-coded for now) -- either explicitly (`--policy=<name>`) or randomly (`--policy=random`).

Continue to support deployment of all filestore and all encrypted OSDs via `--policy=filestore` and `--policy=dmcrypt`.

### CODE REVIEW

**Comment by smithfarm** [comment]
Replaces #1248

**Comment by smithfarm** [comment]
@jschmid1 The git history is pretty messed up, since this is a refactor. I propose to squash all the commits into one. I will of course backport the feature to SES5, but it won't be a cherry-pick.

**Comment by jschmid1** [comment]
> @jschmid1 The git history is pretty messed up, since this is a refactor. I propose to squash all the commits into one. I will of course backport the feature to SES5, but it won't be a cherry-pick.

That's fine.

> See it working here: http://137.74.25.20:8081/ubuntu-2018-07-28_09:24:13-suse:smoke:health-ok-wip-qa-osd-config---basic-openstack/
> 
> especially the part between Stages 1 and 2! The failures are due to #1247

I think we have what we need to bet a better understanding of why things failed. +1

The failures mentioned in #1247 need to be analyzed of course, but for now we have the tests in place and can proceed. 

Imo we also need a way to iteratively run _all_ configurations.

**Comment by smithfarm** [comment]
@jschmid1 This PR *enables* all kinds of testing of OSD configurations, including testing of *all* the configs (in parallel, or sequentially - however you like).

In teuthology, we'll test them all in parallel via this commit: https://github.com/SUSE/ceph/commit/fd9f88656263c7ad6c388e91a5d75937e8620732

**Comment by jschmid1** [comment]
> @jschmid1 This PR enables all kinds of testing of OSD configurations, including testing of all the configs (in parallel, or sequentially - however you like).

If possible, always paralllel :) I just thought of the hardware/resource constraints that would prevent us from doing so. If that's not a problem, let's go with parallel.



> In teuthology, we'll test them all in parallel via this commit: SUSE/ceph@fd9f886

Ah, great :+1:

**Comment by smithfarm** [comment]
@jschmid1 Good, because deploying clusters sequentially is not one of teuthology's strong points :-)

**Pull request merged**
