### PR TITLE
[DNM] Punk's not dead, Punk lives in our hearts, run the new igw smoke test, teuthology pass starts

### PR DESCRIPTION
**Pull request by smithfarm**
Making some changes to the PR CI - need this to test them

### CODE REVIEW

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
@susebot run teuthology deepsea/tier2/igw

**Comment by smithfarm** [comment]
@kshtsk Could you please re-run teuthology deepsea/tier2/igw once https://github.com/SUSE/teuthology/pull/196 is merged?

**Comment by kshtsk** [comment]
@susebot run teuthology deepsea/tier2/igw

**Comment by smithfarm** [comment]
reopening to test the switch from tier1 to tier2

**Comment by kshtsk** [comment]
@susebot run teuthology deepsea:tier2:igw using ses6-deepsea-pr on ecp

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
Looks good - thanks, @kshtsk 

@jschmid1 @rjfd the standard "susebot run teuthology" now runs `deepsea/tier2`, which contains "fs", "rgw", and "igw" deployment/smoke tests (with "nfs-ganesha" to be added soon) in addition to the DeepSea functests.

**Pull request closed without merging**
