### PR TITLE
Create and distribute keyring for ceph-crash

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <ejackson@suse.com>
bnc: 1174004

-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [x] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
```
2020-07-28T18:11:39.682 INFO:teuthology.orchestra.run.target-ses-078.stdout:----------
2020-07-28T18:11:39.683 INFO:teuthology.orchestra.run.target-ses-078.stdout:          ID: start ganesha:
2020-07-28T18:11:39.683 INFO:teuthology.orchestra.run.target-ses-078.stdout:    Function: salt.state
2020-07-28T18:11:39.684 INFO:teuthology.orchestra.run.target-ses-078.stdout:      Result: False
2020-07-28T18:11:39.685 INFO:teuthology.orchestra.run.target-ses-078.stdout:     Comment: Run failed on minions: target-ses-041.ecp.suse.de
2020-07-28T18:11:39.686 INFO:teuthology.orchestra.run.target-ses-078.stdout:     Started: 18:10:57.992204
2020-07-28T18:11:39.687 INFO:teuthology.orchestra.run.target-ses-078.stdout:    Duration: 41506.107 ms
2020-07-28T18:11:39.688 INFO:teuthology.orchestra.run.target-ses-078.stdout:     Changes:
2020-07-28T18:11:39.689 INFO:teuthology.orchestra.run.target-ses-078.stdout:              target-ses-041.ecp.suse.de:
2020-07-28T18:11:39.690 INFO:teuthology.orchestra.run.target-ses-078.stdout:                Name: /etc/ceph/ceph.client.ganesha.target-ses-041.keyring - Function: file.managed - Result: Clean Started: - 18:10:59.867061 Duration: 158.138 ms
2020-07-28T18:11:39.691 INFO:teuthology.orchestra.run.target-ses-078.stdout:                Name: /etc/ceph/ceph.client.rgw.ganesha.target-ses-041.keyring - Function: file.managed - Result: Clean Started: - 18:11:00.077239 Duration: 86.641 ms
2020-07-28T18:11:39.692 INFO:teuthology.orchestra.run.target-ses-078.stdout:                Name: install_ganesha - Function: pkg.installed - Result: Changed Started: - 18:11:12.594022 Duration: 12881.433 ms
2020-07-28T18:11:39.693 INFO:teuthology.orchestra.run.target-ses-078.stdout:                Name: /etc/ganesha/ganesha.conf - Function: file.managed - Result: Changed Started: - 18:11:25.520846 Duration: 77.67 ms
2020-07-28T18:11:39.694 INFO:teuthology.orchestra.run.target-ses-078.stdout:              ----------
2020-07-28T18:11:39.695 INFO:teuthology.orchestra.run.target-ses-078.stdout:                        ID: enable and start nfs-ganesha
2020-07-28T18:11:39.695 INFO:teuthology.orchestra.run.target-ses-078.stdout:                  Function: service.running
2020-07-28T18:11:39.696 INFO:teuthology.orchestra.run.target-ses-078.stdout:                      Name: nfs-ganesha
2020-07-28T18:11:39.697 INFO:teuthology.orchestra.run.target-ses-078.stdout:                    Result: False
2020-07-28T18:11:39.698 INFO:teuthology.orchestra.run.target-ses-078.stdout:                   Comment: Job for nfs-ganesha.service failed because the control process exited with error code.
2020-07-28T18:11:39.699 INFO:teuthology.orchestra.run.target-ses-078.stdout:                            See "systemctl  status nfs-ganesha.service" and "journalctl  -xe" for details.
2020-07-28T18:11:39.700 INFO:teuthology.orchestra.run.target-ses-078.stdout:                   Started: 18:11:36.857528
2020-07-28T18:11:39.701 INFO:teuthology.orchestra.run.target-ses-078.stdout:                  Duration: 2540.094 ms
2020-07-28T18:11:39.702 INFO:teuthology.orchestra.run.target-ses-078.stdout:                   Changes:
2020-07-28T18:11:39.703 INFO:teuthology.orchestra.run.target-ses-078.stdout:
2020-07-28T18:11:39.705 INFO:teuthology.orchestra.run.target-ses-078.stdout:              Summary for target-ses-041.ecp.suse.de
2020-07-28T18:11:39.706 INFO:teuthology.orchestra.run.target-ses-078.stdout:              ------------
2020-07-28T18:11:39.706 INFO:teuthology.orchestra.run.target-ses-078.stdout:              Succeeded: 4 (changed=2)
2020-07-28T18:11:39.707 INFO:teuthology.orchestra.run.target-ses-078.stdout:              Failed:    1
2020-07-28T18:11:39.708 INFO:teuthology.orchestra.run.target-ses-078.stdout:              ------------
2020-07-28T18:11:39.709 INFO:teuthology.orchestra.run.target-ses-078.stdout:              Total states run:     5
2020-07-28T18:11:39.710 INFO:teuthology.orchestra.run.target-ses-078.stdout:              Total run time:  15.744 s
2020-07-28T18:11:39.711 INFO:teuthology.orchestra.run.target-ses-078.stdout:
2020-07-28T18:11:39.712 INFO:teuthology.orchestra.run.target-ses-078.stdout:Summary for target-ses-078.ecp.suse.de_master
2020-07-28T18:11:39.713 INFO:teuthology.orchestra.run.target-ses-078.stdout:-------------
2020-07-28T18:11:39.714 INFO:teuthology.orchestra.run.target-ses-078.stdout:Succeeded: 17 (changed=16)
2020-07-28T18:11:39.715 INFO:teuthology.orchestra.run.target-ses-078.stdout:Failed:     1
```

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
ceph-crash seems to get deployed fine though

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@shyukri something is happening with teuthology

**Comment by shyukri** [comment]
> Commit [6d2687a](https://github.com/SUSE/DeepSea/commit/6d2687ac4859293784994fffcdf15588800320fb) is _NOT OK_ for suite deepsea:tier2.
> Check tests results in the Jenkins job: https://ceph-ci.suse.de/job/pr-deepsea/6/

This job shouldn't have been triggered at all. That's fixed.

**Pull request merged**
