### PR TITLE
packagemanager: fixup updates needed check for zypper dup

### LINKED ISSUE #380: packagemanager.dup: fails to run `zypper dup`
Issue is with `Zypper::_updates_check()`.  `zypper lu` will not determine if upgrades (via `zypper dup`) are needed.

### PR DESCRIPTION
**Pull request by kmroz**
Fixes #380

Signed-off-by: Karol Mroz <kmroz@suse.de>

### CODE REVIEW

**Comment by kmroz** [comment]
This breaks some unit tests... will need to fix.

**Comment by kmroz** [comment]
Re-factored to avoid breaking unit tests.

**Comment by kmroz** [comment]
@jschmid1 - I _think_ you replaced all invocations of ceph.update with ceph.upgrade during our debug session... I've pushed those changes here as well.  Could you take a look please?  We're not relying on maintenance/upgrade/* to perform `zypper up`, correct?  Or would this change modify the expected behaviour?

**Comment by kmroz** [comment]
Works for me as it is now.

**Comment by jschmid1** [comment]
> @jschmid1 - I think you replaced all invocations of ceph.update with ceph.upgrade during our debug session...

Correct

> I've pushed those changes here as well. Could you take a look please? We're not relying on maintenance/upgrade/* to perform zypper up, correct? Or would this change modify the expected behaviour?

No, we only perform a zypper dup but ask the user to update the cluster beforehand.

**Pull request merged**
