### PR TITLE
qa: nfs-ganesha: implement RGW and CephFS+RGW FSAL test cases

### PR DESCRIPTION
**Pull request by smithfarm**
This completes the implementation of the basic test matrix - see "Test Matrix" section in https://gitlab.suse.de/ceph/documentation/blob/master/testing/plan/nfs_ganesha.rst

### CODE REVIEW

**Comment by smithfarm** [comment]
Cannot test this currently due to OVH infrastructure issue.

**Comment by smithfarm** [comment]
Tested and working, more or less, here: http://149.202.189.249:8081/ubuntu-2017-08-07_20:22:28-deepsea:basic:nfs-ganesha-ses5---basic-openstack/

The final `ls -lR` shows the cephfs subdirectory, but I was expecting RGW subdirs as well?

**Comment by smithfarm** [comment]
All three elements of the basic NFS-Ganesha integration test matrix are now implemented, and passing: http://149.202.189.249:8081/ubuntu-2017-08-08_09:29:21-deepsea:basic:nfs-ganesha-ses5---basic-openstack/

**Comment by supriti** [comment]
LGTM.

**Pull request merged**
