### PR TITLE
Improve removal with missing disk

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <ejackson@suse.com>
bnc#1133826
bnc#1134723
-----------------

**Checklist:**
- [x] Added unittests and or functional tests
- [ ] Adapted documentation
- [x] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
> Commit [e57daa2](https://github.com/SUSE/DeepSea/commit/e57daa28765b28e808a97cdc61fbf5ea1a93faa1) is _NOT OK_ for suite deepsea:tier2.
> Check tests results in the Jenkins job: http://ci.ses.suse.de:8080/job/pr-deepsea/236/

2019-06-06T12:29:57.580 DEBUG:teuthology.run_tasks:Unwinding manager internal.lock_machines

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@kshtsk teuthology seems to be broken, may you have a look at it?

**Comment by kshtsk** [comment]
> @kshtsk teuthology seems to be broken, may you have a look at it?

not teuthology, cloud is lacking resources

**Comment by kshtsk** [comment]
@susebot run teuthology

**Pull request merged**
