### PR TITLE
tuned: make stanza names unique

### PR DESCRIPTION
**Pull request by smithfarm**
I don't know if this is really necessary, but it seems like a good practice to
follow.

-----------------

**Checklist:**
~~- [ ] Added unittests and or functional tests~~
~~- [ ] Adapted documentation~~
~~- [ ] Referenced issues or internal bugtracker~~
- [x] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
I think that won't hurt. What do you think @mogeb

**Comment by smithfarm** [comment]
@susebot run teuthology suse

**Comment by smithfarm** [comment]
@jschmid1 @mogeb Since the Stage 3 timeout still happens even with this patch, I no longer care about this PR. Feel free to close it if you don't think it's useful.

**Comment by mogeb** [comment]
Makes sense, thanks @smithfarm I'll keep this practice in mind.

**Comment by smithfarm** [comment]
backport: https://github.com/SUSE/DeepSea/pull/1354

**Pull request merged**
