### PR TITLE
prometheus: fix populate_mgr_scrape_configs states to work with deepsea-cli

### PR DESCRIPTION
**Pull request by rjfd**
Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
I updated the PR CI to run the functional tests via both CLI and non-CLI.

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
The teuthology failure is due to an unrelated bug. The test case using the CLI demonstrates that this PR fixes the bug it claims to be fixing: the `prometheus` and `grafana` roles are present, and the cluster deployment (all the way through Stage 4) succeeds. For details, see the teuthology log:

http://10.86.0.53/ubuntu-2019-03-20_11:17:32-suse:tier1-ses6---basic-openstack/11093/teuthology.log

**Pull request merged**
