### PR TITLE
[backport][SES5] Sync modules before deploying salt-api

### PR DESCRIPTION
**Pull request by smithfarm**
Backport of #917

### CODE REVIEW

**Comment by kshtsk** [comment]
please run health-ok suite

**Comment by kshtsk** [comment]
please run rgw suite

**Comment by kshtsk** [comment]
please run openattic suite

**Comment by kshtsk** [comment]
please run health-ok suite

**Comment by kshtsk** [comment]
please run rgw suite

**Comment by kshtsk** [comment]
please run openattic suite

**Comment by kshtsk** [comment]
please run health-ok suite

**Comment by kshtsk** [comment]
please run health-ok suite

**Comment by kshtsk** [comment]
please run health-ok suite

**Comment by kshtsk** [comment]
please run openattic suite

**Comment by kshtsk** [comment]
please run health-ok suite

**Comment by kshtsk** [comment]
please run openattic suite

**Comment by kshtsk** [comment]
please run rgw suite

**Comment by smithfarm** [comment]
oh, very nice green color :-)

**Pull request merged**
