### PR TITLE
qa: common/deploy: run "zypper ps -s" on all nodes

### PR DESCRIPTION
**Pull request by smithfarm**
**Checklist:**
~~- [ ] Added unittests and or functional tests~~
~~- [ ] Adapted documentation~~
~~- [ ] Referenced issues or internal bugtracker~~
- [x] Ran integration tests successfully ( trigger with @susebot run teuthology )

### CODE REVIEW

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
Backport included in #1289

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology with suse:tear1:health-ok

**Comment by kshtsk** [comment]
@susebot run teuthology with deepsea:basic:health-ok

**Comment by kshtsk** [comment]
@susebot run teuthology for suse:tier1:health-ok

**Comment by smithfarm** [comment]
Added a commit that hopefully fixes #1284

**Comment by smithfarm** [comment]
@susebot run teuthology for suse:tier1:functional

**Comment by smithfarm** [comment]
If `suse/tier1/functional` passes, this should be good to merge.

**Comment by kshtsk** [comment]
@susebot run teuthology for suse:tier1:health-ok

**Comment by kshtsk** [comment]
@susebot run teuthology with deepsea:basic:health-ok

**Comment by kshtsk** [comment]
@susebot run teuthology with deepsea:basic:health-ok

**Comment by smithfarm** [comment]
@kshtsk Note that @denisok fixed `@susebot run teuthology` so it runs `suse/tier1`

**Comment by kshtsk** [comment]
@smithfarm workarounded, I'm replacing it with correct way of handling

**Comment by kshtsk** [comment]
@susebot run teuthology with deepsea:basic:health-ok

**Comment by kshtsk** [comment]
@susebot run teuthology with deepsea:basic:health-ok

**Comment by kshtsk** [comment]
@susebot run teuthology with suse/tier1/functional

**Comment by kshtsk** [comment]
@susebot run teuthology with deepsea:basic:health-ok

**Comment by smithfarm** [comment]
suse:tier1:functional/{clusters/1node4disks.yaml distros/sle_15.yaml exec/functional.yaml tasks.yaml} | 17 min | Passed

**Comment by kshtsk** [comment]
@smithfarm didn't get you're merging ticket even if fails?

**Comment by smithfarm** [comment]
@kshtsk `suse/tier1/functional` contains three test cases: func-migrate.yaml, func-replace.yaml, and functional.yaml. Of these, func-{migrate,replace}.yaml are there for testing PR #1216 which hasn't been merged yet, so they are expected to fail. The third one, functional.yaml, was also failing due to #1284 but that is now fixed thanks to this PR.

**Comment by smithfarm** [comment]
Note: both commits from this PR have been cherry-picked into #1289

**Comment by kshtsk** [comment]
@smithfarm thanks for explanation, as I understand you just could not filter the functional.yaml case.

**Pull request merged**
