### PR TITLE
Conditional reboots and updates

### PR DESCRIPTION
**Pull request by jschmid1**
We had this request multiple times in the past.

Followup to issue #368

### CODE REVIEW

**Comment by swiftgist** [comment]
Would it be easier to have default-noupdate.sls or something?  With two variables, we have other situations to consider.  If I set updates, but not reboots, do we really want to debug why things aren't working because the wrong kernel is running?  Or processes are still using the previous version of a library?

The opposite seems benign.  I am willing to reboot, but I don't want updates. That seems okay, but the workflow is strange.  I want to manually do updates myself, but then I'm willing for Stage 0 to reboot my nodes if the kernel changed.

**Comment by jan--f** [comment]
I also think we should stay consistent with our pillar usage and provide a default-noreboot.sls or so to use with stage_prep_*.

Though imho the default should really be something minimal, i.e. without the updates. But I suppose that is a different issue.

**Comment by jschmid1** [comment]
> Would it be easier to have default-noupdate.sls or something? With two variables, we have other situations to consider. If I set updates, but not reboots, do we really want to debug why things aren't working because the wrong kernel is running? Or processes are still using the previous version of a library?
> I also think we should stay consistent with our pillar usage and provide a default-noreboot.sls or so to use with stage_prep_*.

Understood.

> Though imho the default should really be something minimal, i.e. without the updates. But I suppose that is a different issue.

I fully support that. Even if we tell our users to run a 'Non-Stage' command in order to get updates and reboots. There _definitely_ will be the request to avoid automatic reboots and updates. And imho, telling them to use an alternative stage is not suuper nice.
_\<nit>_ In addition we are duplicating code, which needs to be maintained. _\</nit>_

**Comment by jschmid1** [comment]
figured the resulting amount of files is pretty messy.

1) Updates but no reboots
2) Reboots but no updates
3) Reboots and updates
4) No reboots no updates

**Comment by smithfarm** [comment]
@jschmid1 Which of those 4 will be the default?

**Comment by jschmid1** [comment]
That's what we should agree on. What I hear from i.e. Martin is - Updates are ok, please no reboots.

I personally also vote for:

1) Updates but no reboots

**Comment by swiftgist** [comment]
@jschmid1 if you allow updates, but do not do reboots, what do you expect from the admin?

**Comment by jschmid1** [comment]
Only kernel (and certain other things like glibc) updates do require reboots to take effect. What I read and heard, it's common practice to reboot machines in a predefined maintenance window.

**Comment by jschmid1** [comment]
closed in favor of #419

**Pull request closed without merging**
