### PR TITLE
rgw.py: tolerate a certain number of S3 connection failures

### PR DESCRIPTION
**Pull request by smithfarm**
This commit implements a try-wait loop around the S3 connection
in create_buckets().

Fixes: https://github.com/SUSE/DeepSea/issues/1580
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by theanalyst** [comment]
While this codepath does make sense in the testing suites, in case of a normal cluster, wouldn't it lead to a 100s wait before failure, I don't have strong opinions on whether that is acceptable or not. Is it possible to control the timeout as a parameter that we pass in or so?

**Comment by smithfarm** [comment]
@theanalyst The try-wait loop appears to be useless, as it does nothing to overcome the error. I'm throwing away this entire PR except for the missing "failhard: True".

@jschmid1 The bug appears to be a regression introduced by a recent DeepSea PR, but I'm still bisecting. I don't have the smoking gun yet, but I do know there is one. 

First, I found that the bug reproduces on the tip of master when installed using "make install" (no RPM).

Second, I found that the bug does not reproduce on the v0.9.15 tag when installed using "make install".

So it looks very likely that, very soon, I'll find the exact PR that introduced the bug. I.e. one of these:

```
smithfarm@wilbur:~/src/DeepSea> git log --reverse --oneline --merges v0.9.15..HEAD
8f8f44a4 Merge pull request #1570 from rjfd/wip-cli-fix-prometheus
12b291cd Merge pull request #1577 from smithfarm/wip-fix-functests-symlink
f7cc9bd7 Merge pull request #1474 from votdev/blinking_lights
4271fb2d Merge pull request #1568 from smithfarm/wip-msgr2
8cb39d7e Merge pull request #1575 from rjfd/wip-cli-fix-python2-stderr-redirect
1ddf5463 Merge pull request #1576 from rjfd/wip-cli-wrap-lines
778f8a00 Merge pull request #1578 from SUSE/wip-ipv6
3738bca9 (HEAD -> master, suse/master) Merge pull request #1579 from smithfarm/wip-cepg
```

**Pull request closed without merging**
