### PR TITLE
aa-teardown can fail if apparmor is disabled on the boot command line

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <ejackson@suse.com>
bnc: 1174536

-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [x] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by swiftgist** [comment]
The onfail is like a goto... so adding the failure condition for the binary being present but disabled in the kernel command line.  This causes the state to succeed in that case, but leaves the original behavior intact.

**Comment by jan--f** [comment]
huh...is there a naming conflict or version issue? Cause https://docs.saltstack.com/en/latest/ref/states/requisites.html#onfail reads differently to me. Or at least to goto-like aspect isn't mentioned.

**Comment by swiftgist** [comment]
Take a look at the whole file, it's the same behavior with the previous step.  Also, I did have Martin test in his environment and the state succeeded.  Would you have another solution?

**Comment by jan--f** [comment]
Well who am I to argue with successful testing :)
Only alternative might be adding jinja and I'm always up for avoiding that.

**Comment by jschmid1** [comment]
@susebot run teuthology

**Pull request merged**
