### PR TITLE
ganesha: report runner to give support info about nfs-ganesha

### PR DESCRIPTION
**Pull request by rjfd**
This PR adds a function to the ganesha runner to output the information about the current nfs-ganesha gateways and their configuration.

Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by jschmid1** [comment]
looks good(minus the linter issues), could we get this interweaved in the CI somehow? @smithfarm

**Comment by rjfd** [comment]
@jschmid1 lint issues fixed.

Having this info in the CI logs is a great idea.

**Comment by smithfarm** [comment]
@jschmid1 @rjfd Here is the ganesha smoke test: https://github.com/SUSE/ceph/blob/ses6-downstream-commits/qa/tasks/scripts/ganesha_smoke_test.sh

Please provide details (what to run, when to run it), preferably in the form of a PR :-)

**Comment by smithfarm** [comment]
You could also provide the information in the form of a CI log which is edited to show which command should be run where.

**Comment by rjfd** [comment]
> Please provide details (what to run, when to run it), preferably in the form of a PR :-)

@smithfarm
This report could be run after stage 4 is finished, and also in the middle of the execution of the ganesha_smoke_test.

I can open a PR adding this to the ganesha_smoke_test.sh (for running after stage 4, I don't know where to change), but I have one question, can we run a `salt-run` command in that script?

**Comment by smithfarm** [comment]
@rjfd Running a `salt-run` command (i.e. on the master) after Stage 4 is no problem. Running it in the middle of `ganesha_smoke_test.sh` is somewhat more difficult, because that script is not guaranteed to run on the master node - see https://github.com/SUSE/ceph/blob/ses6-downstream-commits/qa/tasks/deepsea.py#L1867-L1888

There are at least two ways to approach this: either (1) split `ganesha_smoke_test.sh` into two parts, or (2) run the command from the script via `ssh`.

ad 1:

In this scenario, the existing `ganesha_smoke_test.sh` would be split into two scripts - call them "before" and "after" - and the `salt-run` command would be triggered on the master after "before" completes, but before "after" begins.

ad 2:

Alternatively, we could pass the hostname of the master node as an argument to the script, and have the script do something like `ssh $MASTER_NODE sudo salt-run . . .`

**Comment by smithfarm** [comment]
CI integration PR ready for review: https://github.com/SUSE/ceph/pull/331

**Comment by jschmid1** [comment]
What are the next steps here @smithfarm @rjfd ?

**Comment by smithfarm** [comment]
@jschmid1 @rjfd https://github.com/SUSE/ceph/pull/331 has been merged and cherry-picked to `ses6-deepsea-pr`, so I'll trigger the nfs-ganesha test and see what happens.

**Comment by smithfarm** [comment]
@susebot run teuthology deepsea/tier2/nfs-ganesha

**Comment by smithfarm** [comment]
Ganesha report can be seen in all its glory.

**Comment by jschmid1** [comment]
if you'd like to see this feature in SES6 please create a backport for this @rjfd

**Pull request merged**
