### PR TITLE
[SES5][backport] tuned: disable dynamic tuning for all profiles

### PR DESCRIPTION
**Pull request by mogeb**
Signed-off-by: Mohamad Gebai <mgebai@suse.com>
suse internal: bsc#1119260

-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [ ] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
Since the CI is down, is this something you can manually reproduce? @mogeb

**Comment by mogeb** [comment]
@jschmid1 reproduce as in test? If so then yes I have tested it, not through the smoketests though.

**Comment by mogeb** [comment]
Note: this is a backport of https://github.com/SUSE/DeepSea/pull/1490

**Comment by jschmid1** [comment]
> @jschmid1 reproduce as in test? If so then yes I have tested it, not through the smoketests though.

Ok - you should be able to test it through the smoketest though.

`salt-run state.orch ceph.functests.1node.tuned`

should run relatively isolated

**Comment by mogeb** [comment]
@jschmid1 done:
```
# salt-run state.orch ceph.functests.1node.tuned
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
localhost_master:
  Name: Apply mgr tuned states - Function: salt.state - Result: Changed Started: - 20:14:23.474201 Duration: 15133.071 ms
  Name: Apply mon tuned states - Function: salt.state - Result: Changed Started: - 20:14:38.607379 Duration: 15115.459 ms
  Name: Apply osd tuned states - Function: salt.state - Result: Changed Started: - 20:14:53.722943 Duration: 15161.092 ms
  Name: Check tuned for ses roles - Function: salt.state - Result: Changed Started: - 20:15:08.884140 Duration: 15274.011 ms

Summary for localhost_master
------------
Succeeded: 4 (changed=4)
Failed:    0
------------
Total states run:     4
Total run time:  60.684 s
```

**Pull request merged**
