### PR TITLE
Support ceph-iscsi

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <ejackson@suse.com>
-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [ ] Referenced issues or internal bugtracker
- [x] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
looks good, but I think we are missing the `cephprocesses.py` piece here.

**Comment by jschmid1** [comment]
> looks good, but I think we are missing the `cephprocesses.py` piece here.

bump @swiftgist

**Comment by swiftgist** [comment]
This contains the cephprocesses.py and the change to iscsi-gateway.cfg.  The current working rpm is ceph-iscsi-3.0+1551361389.g157b5fd-1.1.noarch

**Comment by swiftgist** [comment]
Not sure why removing 'lrbd' from cephprocesses.py would break the test_report_up_down_down.

**Comment by jschmid1** [comment]
@susebot run teuthology

**Pull request merged**
