### PR TITLE
[backport][ses5] cli: prettyprint: force stdout flush in all stdout writes

### PR DESCRIPTION
**Pull request by jschmid1**
Fixes: #1434

Signed-off-by: Ricardo Dias <rdias@suse.com>
(cherry picked from commit 6adb0081b753cef22d99d7503cef16d8f6535b3d)

backport of #1435 

-----------------

**Checklist:**
- [x] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
> @kshtsk The error is the same as we are seeing in the other PRs. Maybe teardown/redeploy teuthology?

Which error?

**Comment by kshtsk** [comment]
> Commit [b39af34](https://github.com/SUSE/DeepSea/commit/b39af3473696e0aa80c67b23449812c00b4fa238) is _OK_ for suite suse:tier1.
> Check tests results in the Jenkins job: https://ceph-ci.suse.de/job/deepsea-pr/289/

@smithfarm it does not say any error there.

**Comment by smithfarm** [comment]
@kshtsk I was looking at the earlier one. Looks like you have fixed the infra for now, thanks!

**Pull request merged**
