### PR TITLE
[backport][SES5]Reuse OSD ID in migrations, support replace.osds

### PR DESCRIPTION
**Pull request by swiftgist**
These functions are essentially equivalent and bundled together.

Signed-off-by: Eric Jackson <ejackson@suse.com>

### CODE REVIEW

**Comment by swiftgist** [comment]
Note that SLE12SP3 in VMs does not create the `/dev/disk/by-path` symlinks.  This required adjusting the smoketests to handle the "manual" step.

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by jschmid1** [comment]
we need a rebase on that on @swiftgist

**Comment by denisok** [comment]
retest this please

**Comment by denisok** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
[Tasklist for integration tests](https://trello.com/c/Mletjdor/5-tasklist-for-integration-tests)

**Comment by jschmid1** [comment]
[Replace/Migration backports](https://trello.com/c/V3Yp3VZX/10-replace-migration-backports)

**Comment by jschmid1** [comment]
@swiftgist rebase please

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jan--f** [comment]
This is the backport for #1216. See discussion there.

**Pull request merged**
