### PR TITLE
cli: prettyprint: force stdout flush in all stdout writes

### PR DESCRIPTION
**Pull request by rjfd**
Fixes: #1434

Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by smithfarm** [comment]
@jschmid1 The default susebot test does not use the CLI, so it provides absolutely no test coverage for this PR. Let's use `suse/tier0` instead.

**Comment by smithfarm** [comment]
Opened https://github.com/SUSE/DeepSea/issues/1438 for the above CI issue. Presumably it will affect all PRs from now on?

**Comment by smithfarm** [comment]
@susebot run teuthology suse/tier0

**Comment by kshtsk** [comment]
> Opened #1438 for the above CI issue. Presumably it will affect all PRs from now on?

You mean after merging this PR, don't you?

**Comment by kshtsk** [comment]
I wonder how flushing buffers can affect the repo results refresh issue, maybe it is introduced in other PR?

**Comment by smithfarm** [comment]
> You mean after merging this PR, don't you?

No. I would be surprised if #1438 were caused by this PR, since this PR only touches the CLI code and the failed test is non-CLI.

My assumption is that if #1438 is reproducing in this PR, it will reproduce in others as well.

**Comment by kshtsk** [comment]
@smithfarm right, we need to merge this one.

**Pull request merged**
