### PR TITLE
Use correct config name for Dashboard SSL port

### PR DESCRIPTION
**Pull request by votdev**
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1129225

Signed-off-by: Volker Theile <vtheile@suse.com>

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [x] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by votdev** [comment]
> From the CI:
> 
> ```
> 2019-05-10T11:32:36.393 INFO:teuthology.orchestra.run.target192168000062.stdout:[11/30] Executing state ceph.dashboard...
> 2019-05-10T11:32:38.021 INFO:teuthology.orchestra.run.target192168000062.stdout:         |_  target192168000062.teuthology: set dashboard ssl port(ceph config set mgr mgr/dashboard/ssl_server_port 8443) fail
> 2019-05-10T11:32:38.046 INFO:teuthology.orchestra.run.target192168000062.stdout:         target192168000062.teuthology... fail
> ```

Can not reproduce this locally in a SLE15 Vagrant cluster using DeepSea 0.9.18 via CLI or adapted SLS file.

```
[11/30]   ceph.dashboard on
          admin.ceph..................................................................... ✓ (2s)
            |_ cmd.run(ceph config set mgr mgr/dashboard/ssl_server_port 8443)........... ✓
            |_ cmd.run(ceph dashboard create-self-signed-cert)........................... ✓

```

```
admin:/home/vagrant # deepsea --version
deepsea 0.9.18+git.0.a21d7b040
admin:/home/vagrant # ceph config set mgr mgr/dashboard/ssl_server_port 8443
admin:/home/vagrant # echo $?
0
```

Any ideas?

**Comment by jschmid1** [comment]
A bit further down the log:

```
 set dashboard ssl port: Command "ceph config set mgr mgr/dashboard/ssl_server_port 8443" run
 stdout:
 stderr: Error EINVAL: unrecognized config option 'mgr/dashboard/ssl_server_port' <---- this
```

I'd assume that the CI doesn't have an up-to-date ceph version.

> ceph-mgr-14.2.0.300+gacd2f2b9e1-1.1.x86_64.rpm

What's your version @votdev ?

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
same thing :/

**Comment by votdev** [comment]
> A bit further down the log:
> 
> ```
>  set dashboard ssl port: Command "ceph config set mgr mgr/dashboard/ssl_server_port 8443" run
>  stdout:
>  stderr: Error EINVAL: unrecognized config option 'mgr/dashboard/ssl_server_port' <---- this
> ```
> 
> I'd assume that the CI doesn't have an up-to-date ceph version.
> 
> > ceph-mgr-14.2.0.300+gacd2f2b9e1-1.1.x86_64.rpm
> 
> What's your version @votdev ?

ceph version 14.2.1-345-g040ffffe0e (040ffffe0e8b6db713d06fa487c2811b87884973) nautilus (stable)

**Comment by votdev** [comment]
OK, Ceph 14.2.1 is required, see http://tracker.ceph.com/issues/39001 for the feature that added this config setting.

I'm currently asking myself if it is necessary to check Ceph version now because for <= 14.2.0 the config option is ``server_port`` and for >= 14.2.1 it will be ``ssl_server_port``.

**Comment by jschmid1** [comment]
@kshtsk @smithfarm can we update `ceph` in our CI to be >= 14.2.1 ?

**Comment by tserong** [comment]
> I'm currently asking myself if it is necessary to check Ceph version now because for <= 14.2.0 the config option is `server_port` and for >= 14.2.1 it will be `ssl_server_port`

I dunno... Is anyone (aside from our CI :-/) really likely to be using the latest DeepSea with <= 14.2.0?

**Comment by smithfarm** [comment]
@votdev I tend to agree with @tserong . . . also DeepSea does not (currently) have an explicit "Requires: ceph" in the spec file. I'm not sure it makes sense to add one, either, since that would cause all the ceph RPMs to be installed on the admin node, where they probably wouldn't be needed.

**Comment by rjfd** [comment]
I don't think we need to check the ceph version. We can assume that this DeepSea code will run with Ceph 14.2.1

**Comment by smithfarm** [comment]
@susebot run teuthology

**Pull request merged**
