### PR TITLE
Refactor dashboards

### PR DESCRIPTION
**Pull request by jan--f**
This PR unifies the dashboards looks and behaviours. Additionally A few Panels were chaged or added, most notably the PGs and OSD Utilisation pannels.

### CODE REVIEW

**Comment by jan--f** [comment]
@susebot run teuthology

**Comment by jan--f** [comment]
No good way to check the actual dashboards. We could however at least check that grafana runs after deployment. Commit coming up.

**Comment by jan--f** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
failure1)


```
Data failed to compile:
----------
Specified SLS ceph.functests.1node.grafana in saltenv base is not available on the salt master or through a configured fileserver
```
pretty much expected because there is no entry in the Makefile.


failure2/3)


That's the known lrbd issue

```
 Comment: Service lrbd has been enabled, and is dead
```

**Comment by jan--f** [comment]
@susebot run teuthology suse/tier1/functional

**Pull request merged**
