### PR TITLE
populate should overwrite the stack/default tree at all times

### PR DESCRIPTION
**Pull request by jan--f**
Signed-off-by: Jan Fajerski <jfajerski@suse.com>

### CODE REVIEW

**Comment by jschmid1** [comment]
retest this please

**Comment by jschmid1** [comment]
I think we really need to communicate this *before* people upgrade to the new version.

Would you mind doing a write-up and hand that over to Tomas?

**Comment by jan--f** [comment]
@jschmid1 not sure what to communicate. This should be transparent to users. It only overwrites the default tree which is there specificially for our use and customers should have no business there anyway. Pillar data from `/srv/pillar/ceph/stack` will still overwrite the default tree.

**Comment by jschmid1** [comment]
> or our use and customers should have no business there anyway

with an emphasis on the  _should_  :> 

I was under the impression that the global.yaml will also be overwritten, and if I'm not mistaken we reference that a couple of times in our documentation.

**Comment by jan--f** [comment]
> I was under the impression that the global.yaml will also be overwritten, and if I'm not mistaken we reference that a couple of times in our documentation.

That is `/srv/pillar/ceph/stack/default/cluster/global.yml` (maybe silghtly different path but the default tree in any case)

**Comment by jschmid1** [comment]
ah, right. I thought about the /srv/pillar/ceph/global.yaml. No objections then

**Pull request merged**
