### PR TITLE
ganesha: don't run the upgrade on fresh nodes

### PR DESCRIPTION
**Pull request by rjfd**
Signed-off-by: Ricardo Dias <rdias@suse.com>

Fixes: bsc#1148405

Description:

-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [ ] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
I'd assume this is somehow tested by the upgrade tests.. Can you confirm this @smithfarm ?

**Comment by rjfd** [comment]
@jschmid1 I've manually tested the upgrade as well.

**Comment by smithfarm** [comment]
@jschmid Which upgrade tests are you referring to? There is a SES5 -> 6 upgrade test that is currently a WIP, and that will (at the very least) do a basic ganesha deployment on SES5 and check its sanity post-upgrade.

**Comment by jschmid1** [comment]
> @jschmid Which upgrade tests are you referring to? There is a SES5 -> 6 upgrade test that is currently a WIP, and that will (at the very least) do a basic ganesha deployment on SES5 and check its sanity post-upgrade.

@smithfarm In that case I'm referring to that upgrade test :). Would it be possible to run the test on this branch?

**Comment by jschmid1** [comment]
> @jschmid I don't think it's ready for prime time.

I think we did run it from time to time in the past, right?

**Comment by jschmid1** [comment]
This needs rebasing now :/ @rjfd 

I'd like to have this verified automatically.. rebasing causes issues :)

**Comment by rjfd** [comment]
retest this please

**Comment by rjfd** [comment]
rebase done, all checks passed

**Pull request merged**
