### PR TITLE
monitoring: manage salt's fileserver cache in monitoring deployment

### PR DESCRIPTION
**Pull request by jan--f**
Signed-off-by: Jan Fajerski <jfajerski@suse.com>

### CODE REVIEW

**Comment by jan--f** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
retest this please

**Comment by jschmid1** [comment]
`http://storage-ci.suse.de:8080` is still not reachable yet as it seems

**Comment by jschmid1** [comment]
retest this please

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
the failed test looks unrelated.. but since the only test that actually tests the monitoring fails, we need a second testrun

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
sigh ..

**Comment by kshtsk** [comment]
@jschmid1 I'm sorry about this, but internal cloud is still not working as expected

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by rjfd** [comment]
Failure is unrelated:
```
iscsi_upgrade.validate (/srv/modules/runners/iscsi_upgrade.py):
  Error while checking if lrbd is installed in target192168000128.teuthology
  'iscsi' __virtual__ returned False: No module named 'netaddr'
```

**Comment by rjfd** [comment]
The CI failure is fixed in PR #1671. I also tested this PR in my local environment and it looks good. IMO we can merge this PR.

**Comment by kshtsk** [comment]
@rjfd can we retest this PR after merged #1671

**Pull request merged**
