### PR TITLE
FIX issue that would make benchmark.baseline fail if an osd is removed 

### PR DESCRIPTION
**Pull request by plexorama**
Description:

The following error occurs if an osd is removed and benchmark is run after that:

```
admin-server:/ # salt-run state.orch ceph.benchmarks.baseline

Running osd benchmarks..............[ERROR   ] Exception occurred in runner benchmark.baseline: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/srv/modules/runners/benchmark.py", line 284, in baseline
    parsed_results = [ast.literal_eval(r[master_minion]) for r in results]
  File "/usr/lib64/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib64/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    Error ENOENT: problem getting command descriptions from osd.2
               ^
SyntaxError: invalid syntax

admin-server_master:
----------
          ID: osd bench
    Function: salt.runner
        Name: benchmark.baseline
      Result: False
     Comment: Exception occurred in runner benchmark.baseline: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
                  data['return'] = self.functions[fun](*args, **kwargs)
                File "/srv/modules/runners/benchmark.py", line 284, in baseline
                  parsed_results = [ast.literal_eval(r[master_minion]) for r in results]
                File "/usr/lib64/python2.7/ast.py", line 49, in literal_eval
                  node_or_string = parse(node_or_string, mode='eval')
                File "/usr/lib64/python2.7/ast.py", line 37, in parse
                  return compile(source, filename, mode, PyCF_ONLY_AST)
                File "<unknown>", line 1
                  Error ENOENT: problem getting command descriptions from osd.2
                             ^
              SyntaxError: invalid syntax
     Started: 16:41:40.856555
    Duration: 25107.797 ms
     Changes:   

Summary for admin-server_master
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  25.108 s
```

-----------------

[Please find more information on how to run integration tests here](https://github.com/SUSE/DeepSea/wiki/Integration-tests)

### CODE REVIEW

**Comment by jschmid1** [comment]
Hey @plexorama thanks for your contribution. Much appreciated.

While 'osd.list' is a mine and should actually reflect the current state of the cluster I don't see why this patch has any downsides.

It'd be still possible to update the mines before calling a baseline benchmark though.. But still, I don't see any advantage in using a mine here. +1 from my side

**Comment by swiftgist** [comment]
Without the `client_glob`, won't the benchmark always run on all minions?

**Comment by jan--f** [comment]
@swiftgist is correct. The intend was to be able to run on a subset of OSDs as well.

I'd rather be in favour of deugging why ```osd.list``` seems to be broken. How can I reproduce this?

**Comment by plexorama** [comment]
@jan--f to reproduce it, create a cluster with a couple osds (for example 5). then simply create a hole in the sequence, ie: remove osd.3 and there you go.

**Comment by swiftgist** [comment]
@plexorama I'll bet the grains aren't updated.  If you still have your setup available, does the following cause the benchmark to succeed?

```
salt-run remove.osd 3
salt 'minionX' osd.retain
```

If that's the case, we should probably open (or maybe re-open) an issue about when to update the grains as part of other utilities.  I don't believe the current `retain` function is smart enough to delete just one entry.

**Comment by kshtsk** [comment]
retest this please

**Comment by jan--f** [comment]
> I don't believe the current retain function is smart enough to delete just one entry.

Agreed. We have seen issues when users execute ceph commands to remove an OSD and DeepSea misses such updates.

In any case we can go ahead with this. Fixing retain is a separate issue.

**Pull request merged**
