### PR TITLE
pylintrc: Disable W8410 check

### PR DESCRIPTION
**Pull request by gekios**
I propose disabling W8410 - 3rd-party-module-not-gated, in order to fix the CI
failures that got introduced by server upgrade to Leap 15.1.

Signed-off-by: Georgios Kyratsas <gkyratsas@suse.com>

Description:

-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [ ] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jan--f** [comment]
huh any idea why pylint suddenly thinks `os` is a 3rd party module?

**Comment by gekios** [comment]
Yeah actually I noticed this as well and after googling a bit it seems to be missing from all the lists that make`known_std_modules` https://github.com/saltstack/salt-pylint/blob/37d7a63ea808fd42c68378ddf6a5429570c800ac/saltpylint/thirdparty.py#L68

**Comment by gekios** [comment]
Hmmm, I added every module that it was complaining about in `allowed-3rd-party-modules` and it passed but is this the right approach?

**Comment by jschmid1** [comment]
probably not, but it lets us move ahead :>

**Pull request merged**
