### PR TITLE
remove diagnose states. The net runner takes over this functionality

### PR DESCRIPTION
**Pull request by jan--f**
Signed-off-by: Jan Fajerski <jfajerski@suse.com>

### CODE REVIEW

**Comment by swiftgist** [comment]
Looks fine.  Think I would like to pursue the failed health checks though.  (I know they are not directly related here.)

**Comment by kshtsk** [comment]
please run openattic suite

**Comment by kshtsk** [comment]
please run health-ok suite

**Comment by kshtsk** [comment]
please run rgw suite

**Pull request merged**
