### PR TITLE
Add is-failed to systemd checks

### PR DESCRIPTION
**Pull request by jschmid1**
I still don't quite see where to inject the `is-failed` check..

Here's the process: (exemplary for stage.0)

```
> call ceph.stage.0
    > call ceph.restart
        > call ceph.restart.mon ( loop over mons )
            > call ceph.processes
                > call cephprocesses.wait
                    > call cephprocesses.check ( in loop )
            > call ceph.mon.restart
```

When we add a 'is-failed' check in `cephprocesses.check()` we _will_ return a `False` back to wait(). For `wait()` it doesn't matter if this is because there hasn't been a process(pid) or if the process failed to start; In either case it will return `False` an wait() will continue trying to get a positive result until the `timeout` is expired.

Hooking in wait() to check if a failed `check()` is due to a 'is-failed' or a missing pid is also not easily possible without changing the way we report failures. Doing this just to _maybe_ reduce wait time is not worthy in my opinion.

I anyways implemented the call as it might come in handy later.

In addition I fixed a bug in `radosgw`'s disabled/enabled detection and ran a autolinter over the file.

Signed-off-by: Joshua Schmid <jschmid@suse.de>

-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [ ] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
I can remember this being a chicken-egg-problem. This sat for a while.. I need to come back to this eventually..

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
retest this please

**Comment by jschmid1** [comment]
Stale, please re-open when this gets active again

**Pull request closed without merging**
