### PR TITLE
Revert "orchestrator: disable orchestrator for now"

### PR DESCRIPTION
**Pull request by smithfarm**
This reverts commit 9d0baa4ce142e554c6a35ea109337b10eb3be8d3.

Signed-off-by: Nathan Cutler <ncutler@suse.com>

Fixes #

Description:

-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [ ] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by smithfarm** [comment]
@susebot run teuthology

**Comment by rjfd** [comment]
@smithfarm we can't revert his right away because it will break the nfs-ganesha and iscsi management features of ceph-dashboard.

**Comment by smithfarm** [comment]
@rjfd Ack. I just want to make sure the orchestrator functests are passing.

**Comment by smithfarm** [comment]
@tserong The functest is still failing :-(

```
2019-03-27T16:29:02.878 INFO:teuthology.orchestra.run.target192168000020.stdout:----------
2019-03-27T16:29:02.878 INFO:teuthology.orchestra.run.target192168000020.stdout:          ID: check orchestrator
2019-03-27T16:29:02.878 INFO:teuthology.orchestra.run.target192168000020.stdout:    Function: salt.state
2019-03-27T16:29:02.878 INFO:teuthology.orchestra.run.target192168000020.stdout:      Result: False
2019-03-27T16:29:02.879 INFO:teuthology.orchestra.run.target192168000020.stdout:     Comment: Run failed on minions: target192168000020.teuthology
2019-03-27T16:29:02.879 INFO:teuthology.orchestra.run.target192168000020.stdout:     Started: 16:28:53.390039
2019-03-27T16:29:02.879 INFO:teuthology.orchestra.run.target192168000020.stdout:    Duration: 8698.753 ms
2019-03-27T16:29:02.879 INFO:teuthology.orchestra.run.target192168000020.stdout:     Changes:
2019-03-27T16:29:02.879 INFO:teuthology.orchestra.run.target192168000020.stdout:              target192168000020.teuthology:
2019-03-27T16:29:02.880 INFO:teuthology.orchestra.run.target192168000020.stdout:                Name: ceph orchestrator status | grep 'Backend: deepsea' - Function: cmd.run - Result: Changed Started: - 16:28:54.806277 Duration: 680.742 ms
2019-03-27T16:29:02.880 INFO:teuthology.orchestra.run.target192168000020.stdout:                Name: ceph orchestrator status | grep 'Available: True' - Function: cmd.run - Result: Changed Started: - 16:28:55.487663 Duration: 744.163 ms
2019-03-27T16:29:02.880 INFO:teuthology.orchestra.run.target192168000020.stdout:              ----------
2019-03-27T16:29:02.880 INFO:teuthology.orchestra.run.target192168000020.stdout:                        ID: test "$(ceph orchestrator service ls | grep -e ^mon -e ^mgr | wc -l)" -gt 2
2019-03-27T16:29:02.880 INFO:teuthology.orchestra.run.target192168000020.stdout:                  Function: cmd.run
2019-03-27T16:29:02.880 INFO:teuthology.orchestra.run.target192168000020.stdout:                    Result: False
2019-03-27T16:29:02.881 INFO:teuthology.orchestra.run.target192168000020.stdout:                   Comment: Command "test "$(ceph orchestrator service ls | grep -e ^mon -e ^mgr | wc -l)" -gt 2" run
2019-03-27T16:29:02.881 INFO:teuthology.orchestra.run.target192168000020.stdout:                   Started: 16:28:56.232421
2019-03-27T16:29:02.881 INFO:teuthology.orchestra.run.target192168000020.stdout:                  Duration: 5818.658 ms
2019-03-27T16:29:02.881 INFO:teuthology.orchestra.run.target192168000020.stdout:                   Changes:
2019-03-27T16:29:02.881 INFO:teuthology.orchestra.run.target192168000020.stdout:                            ----------
2019-03-27T16:29:02.881 INFO:teuthology.orchestra.run.target192168000020.stdout:                            pid:
2019-03-27T16:29:02.881 INFO:teuthology.orchestra.run.target192168000020.stdout:                                68692
2019-03-27T16:29:02.882 INFO:teuthology.orchestra.run.target192168000020.stdout:                            retcode:
2019-03-27T16:29:02.882 INFO:teuthology.orchestra.run.target192168000020.stdout:                                1
2019-03-27T16:29:02.882 INFO:teuthology.orchestra.run.target192168000020.stdout:                            stderr:
2019-03-27T16:29:02.882 INFO:teuthology.orchestra.run.target192168000020.stdout:                            stdout:
2019-03-27T16:29:02.882 INFO:teuthology.orchestra.run.target192168000020.stdout:
2019-03-27T16:29:02.882 INFO:teuthology.orchestra.run.target192168000020.stdout:              Summary for target192168000020.teuthology
2019-03-27T16:29:02.883 INFO:teuthology.orchestra.run.target192168000020.stdout:              ------------
2019-03-27T16:29:02.883 INFO:teuthology.orchestra.run.target192168000020.stdout:              Succeeded: 2 (changed=3)
2019-03-27T16:29:02.883 INFO:teuthology.orchestra.run.target192168000020.stdout:              Failed:    1
2019-03-27T16:29:02.883 INFO:teuthology.orchestra.run.target192168000020.stdout:              ------------
2019-03-27T16:29:02.883 INFO:teuthology.orchestra.run.target192168000020.stdout:              Total states run:     3
2019-03-27T16:29:02.883 INFO:teuthology.orchestra.run.target192168000020.stdout:              Total run time:   7.244 s
2019-03-27T16:29:02.883 INFO:teuthology.orchestra.run.target192168000020.stdout:
2019-03-27T16:29:02.884 INFO:teuthology.orchestra.run.target192168000020.stdout:Summary for target192168000020.teuthology_master
2019-03-27T16:29:02.884 INFO:teuthology.orchestra.run.target192168000020.stdout:-------------
2019-03-27T16:29:02.884 INFO:teuthology.orchestra.run.target192168000020.stdout:Succeeded: 69 (changed=69)
2019-03-27T16:29:02.884 INFO:teuthology.orchestra.run.target192168000020.stdout:Failed:     1
2019-03-27T16:29:02.884 INFO:teuthology.orchestra.run.target192168000020.stdout:-------------
2019-03-27T16:29:02.884 INFO:teuthology.orchestra.run.target192168000020.stdout:Total states run:     70
2019-03-27T16:29:02.885 INFO:teuthology.orchestra.run.target192168000020.stdout:Total run time:  475.140 s
```

**Pull request closed without merging**
