### PR TITLE
Wip split output master

### PR DESCRIPTION
**Pull request by swiftgist**
Forward port: #1795

-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [ ] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by gekios** [comment]
Repos are not up to date so there are dependency issues with igw test. 
```
2019-11-18T15:49:31.789 INFO:teuthology.orchestra.run.target192168000135.stdout:    install ceph-iscsi dependencies: An error was encountered while installing package(s): Zypper command failure: Running scope as unit: run-r9cfb29b7d0bb48f5a2e54202c4bdc1a2.scope
2019-11-18T15:49:31.790 INFO:teuthology.orchestra.run.target192168000135.stdout:    enable tcmu-runner: The named service tcmu-runner is not available
2019-11-18T15:49:31.790 INFO:teuthology.orchestra.run.target192168000135.stdout:    install ceph-iscsi: An error was encountered while installing package(s): Zypper command failure: Running scope as unit: run-r7338872761044908a1baef7ba77cddad.scope
2019-11-18T15:49:31.790 INFO:teuthology.orchestra.run.target192168000135.stdout:    enable rbd-target-api: The named service rbd-target-api is not available
2019-11-18T15:49:33.641 ERROR:tasks.deepsea.orch:orchestration ceph.stage.4 failed. Creating /var/log/journalctl.log with output of "journalctl --all"!```

**Comment by gekios** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
The ceph-iscsi dependency issue still remains. Is that something you can fix @gekios ?

**Comment by jschmid1** [comment]
We have two commits here while the original PR only has one. 

https://github.com/SUSE/DeepSea/pull/1795/commits vs https://github.com/SUSE/DeepSea/pull/1799/commits

Is this a compatibility issue or was the commit https://github.com/SUSE/DeepSea/pull/1799/commits/eb85e994a41b6423c0901f124561d346b5044936 just missing? @swiftgist

**Comment by swiftgist** [comment]
Yes, the commit didn't apply cleanly since it depended on the other.

**Comment by gekios** [comment]
@susebot run teuthology

**Comment by gekios** [comment]
(Checking if the repos got updated)

**Comment by jschmid1** [comment]
let me know when it's ready to merge @swiftgist

**Pull request merged**
