### PR TITLE
Correct spelling typo

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <ejackson@suse.com>

bnc: 1154489
-----------------

**Checklist:**
- [ ] Added unittests and or functional tests
- [ ] Adapted documentation
- [x] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
rebase pls

**Comment by jschmid1** [comment]
retest this please

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@swiftgist  The unittest need to be adapted.

from the make-test output:

```
assert 'On or more of your minions have updates pending that might cause ceph-daemons to restart. This might extend the duration of this Stage depending on your cluster size.' in "One or more of your minions have updates pending that might cause ceph-daemons to restart. This might extend the dura...which packages will be updated, you can get the full list with salt -I 'cluster:ceph' packagemanager.list_ceph_updates"
```

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@swiftgist see: https://storage-ci.suse.de/job/pr-deepsea-make-test/776/testReport/tests.unit.runners.test_validate/TestValidation/test_ceph_updates_1/

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Pull request merged**
