### PR TITLE
fix _insert_replace_flag func header bsc#1110939

### PR DESCRIPTION
**Pull request by jschmid1**
Fixes bsc#1110939

Description:
commit 1)
Change order of arg passing
commit 2)
In some cases we get `None` from

`content = yaml.safe_load(destroyed)`

~This probably should be factored into a separate function rather than wildly adding if statements..~

Done

I also refactored the yaml.dump code

TODO:
 - [x] refactor
 - [x] add tests

I had to refactor the tests quite a bit. They look more composed imo and should be easier to read and adapt in case of change.

-----------------

**Checklist:**
- [x] Added unittests and or functional tests
~- [ ] Adapted documentation~
- [x] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
retest this please

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@kshtsk 

```
+ [[ '' == \m\a\s\t\e\r ]]
+ [[ '' == \S\E\S\5 ]]
+ [[ '' == \S\E\S\4 ]]
+ echo 'ERROR: Unsupported branch'
ERROR: Unsupported branch
```

From the deepsea-make-rpm

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
retest this please

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
cool, this is an actual failure. looking into that

**Comment by kshtsk** [comment]
@tserong Yeah, I'm in the middle of redeploying server
@susebot run teuthology

**Comment by jschmid1** [comment]
issue addressed, will schedule a test run once ovh is happy again.

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
and there is an issue again @smithfarm @kshtsk 

```
CalledProcessError: Command 'flock --close --timeout 28800 /tmp/teuthology-server-create.lock openstack --quiet server create  -f json  --image 'teuthology-sle-12.3-x86_64' --flavor 's1-8' --key-name teuth-ci  --user-data /tmp/tmp_N2LTD  --min 1 --max 1 --security-group teuth-ci-worker --property teuthology=513c578151556b0b1e6142df11310ab0 --property ownedby=158.69.66.191 --wait  target' returned non-zero exit status 1
2018-10-15T09:10:17.920 DEBUG:teuthology.run_tasks:Unwinding manager internal.lock_machines
```

**Comment by kshtsk** [comment]
@jschmid1 I expect this kind of failures, this particular image is broken and requires to rebuild

**Comment by jschmid1** [comment]
> @jschmid1 I expect this kind of failures, this particular image is broken and requires to rebuild

Could you keep me posted on when the rebuild is done @kshtsk ?

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
[[Bug 1110939] New: replace.osd returns an error for the minion profile](https://trello.com/c/skbfwEh7/81-bug-1110939-new-replaceosd-returns-an-error-for-the-minion-profile)

**Pull request merged**
