### PR TITLE
keyrings: remove x from rgw mon caps; not needed

### PR DESCRIPTION
**Pull request by jan--f**
Description:
Least permissive is the name of the game. 

-----------------

**Checklist:**
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jan--f** [comment]
@susebot run teuthology

**Comment by theanalyst** [comment]
upstream docs also mention the need for only `rw` http://docs.ceph.com/docs/master/man/8/radosgw/?highlight=allow%20rwx#configuration

**Comment by kshtsk** [comment]
@susebot run teuthology

**Comment by kshtsk** [comment]
@jan--f could you please rebase?

**Comment by kshtsk** [comment]
The deepsea-make-rpm failed due to docker issues, now it's fixed and should be working.

**Comment by kshtsk** [comment]
retest this please

**Comment by jan--f** [comment]
Changed my mind...probably not a good idea to change it like this.

**Comment by jschmid1** [comment]
> Changed my mind...probably not a good idea to change it like this.

Can you explain _why_ this was not a good idea? @jan--f

**Comment by jschmid1** [comment]
Ah, explanation in the backport PR -> https://github.com/SUSE/DeepSea/pull/1396#issuecomment-422372502

**Pull request closed without merging**
