### PR TITLE
core: add osds_per_device flag

### PR DESCRIPTION
**Pull request by jschmid1**
This was still missing. See wiki

-----------------

**Checklist:**
- [x] Added unittests and or functional tests
~- [ ] Adapted documentation~ changed in the wiki soon
~- [ ] Referenced issues or internal bugtracker~
- [x] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
> Commit [d8fce45](https://github.com/SUSE/DeepSea/commit/d8fce45225fe6127a520ae28c7d7e5c42dc1b732) is _NOT OK_ for suite deepsea:tier2.
> Check tests results in the Jenkins job: http://ci.ses.suse.de:8080/job/pr-deepsea/248/

I'll take 

``` 
/usr/share/ceph/dashboard-e2e/dashboard_e2e_tests.sh: No such file or directory
```

as unrelated

**Comment by jschmid1** [comment]
> > Commit [d8fce45](https://github.com/SUSE/DeepSea/commit/d8fce45225fe6127a520ae28c7d7e5c42dc1b732) is _NOT OK_ for suite deepsea:tier2.
> > Check tests results in the Jenkins job: http://ci.ses.suse.de:8080/job/pr-deepsea/248/
> 
> I'll take
> 
> ```
> /usr/share/ceph/dashboard-e2e/dashboard_e2e_tests.sh: No such file or directory
> ```
> 
> as unrelated

Nevertheless, @kshtsk or @smithfarm might be interested in this?

**Comment by smithfarm** [comment]
@kshtsk Please update Deepsea PR CI to the latest Devel:Storage:6.0 artifacts.

**Pull request merged**
