### PR TITLE
[SES6] Evacutate OSDs simultaneously when removing OSDs

### PR DESCRIPTION
**Pull request by swiftgist**
Signed-off-by: Eric Jackson <swiftgist@gmail.com>
bnc: 1154096
-----------------

**Checklist:**
- [x] Added unittests and or functional tests
- [ ] Adapted documentation
- [x] Referenced issues or internal bugtracker
- [ ] Ran integration tests successfully (trigger with "@susebot run teuthology" in a GitHub comment; see the [wiki](https://github.com/SUSE/DeepSea/wiki/Testing) for more information)

### CODE REVIEW

**Comment by swiftgist** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
> Commit [20ef390](https://github.com/SUSE/DeepSea/commit/20ef390ad32c7b10543a7b885c0d9412715d7c5c) is _NOT OK_ for suite deepsea:tier2.
> Check tests results in the Jenkins job: http://ci.ses.suse.de:8080/job/pr-deepsea/339/

It looks like we're still having issues with the osd migration tests. Would you please have a look.

**Comment by mgfritch** [comment]
> > Commit [20ef390](https://github.com/SUSE/DeepSea/commit/20ef390ad32c7b10543a7b885c0d9412715d7c5c) is _NOT OK_ for suite deepsea:tier2.
> > Check tests results in the Jenkins job: http://ci.ses.suse.de:8080/job/pr-deepsea/339/
> 
> It looks like we're still having issues with the osd migration tests. Would you please have a look.

Perhaps we need to port the following commit from PR #1786 ?

https://github.com/SUSE/DeepSea/commit/b5e9db6e564e389d34e53eabd33638970a77f85e

**Comment by jschmid1** [comment]
what's the status here @swiftgist

**Comment by swiftgist** [comment]
Originally, I just did this as a separate backport not knowing how long #1786 would take.  But since #1786 does contain this commit, it's fine to close this one.

**Pull request closed without merging**
