### PR TITLE
restarts: if no fs is present, restart mds without coordination

### PR DESCRIPTION
**Pull request by jan--f**
Signed-off-by: Jan Fajerski <jfajerski@suse.com>
(cherry picked from commit 01fc518e4102d719aac7defadff374d8ee4c1948)

Fixes: bsc#1110528

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
@kshtsk The CI seems to choke on some tests:

```
MaxWhileTries: 'volume target192168000079-1' reached maximum tries (3) after waiting for 30 seconds
2019-07-08T07:26:33.566 DEBUG:teuthology.run_tasks:Unwinding manager internal.lock_machines
```

Would you have a look?

**Comment by kshtsk** [comment]
> @kshtsk The CI seems to choke on some tests:
> 
> ```
> MaxWhileTries: 'volume target192168000079-1' reached maximum tries (3) after waiting for 30 seconds
> 2019-07-08T07:26:33.566 DEBUG:teuthology.run_tasks:Unwinding manager internal.lock_machines
> ```
> 
> Would you have a look?

That's ECP issue.

**Comment by kshtsk** [comment]
@susebot run teuthology

**Pull request merged**
